PyCQA/isort

ACKNOWLEDGEMENTS.md, README.md, isort/hooks.py, isort/isort.py
A git hook for isort. Can be called from pre-commit to either prevent commit or just warn about problems.
I had to make sure file_contents took precedence over file_name - it passes in staged contents from the git repo without needing to create tempfiles, but stlil needs to pass in the original filename so that SortImports can report which files have problems. I hope this won't cause problems.
=> Added git hook and documentation

isort/isort.py
I ran isort on isort.py and the line for `isort:imports` found and modified itself. Fixing that by breaking up strings.
=> Prevent line containing isort:import tripping up over itself

isort/settings.py
It is a bit weird to have an `[isort]` section in a `setup.cfg` file, but to require a `[settings]` section if it is in `~/.isort.cfg`.
At least, I had to look at the isort source code to figure out why it wasn't picking up my settings :-)
=> Accept [isort] section in ~/.isort.cfg

isort/settings.py
Under windows system, if the `.editorconfig` file is not CRLF ended, after reading file using `file.readline()`, the `file.tell()` will give negative values, which at last raises `IOError`: "[Errno 22] Invalid argument". 
This patch open config files in "[universal newlines](https://docs.python.org/2/glossary.html#term-universal-newlines)" mode, which treat all line endings as '\n', hopefully fixes this issue.
@timothycrosley, I don't have enough tests, just let you know about this issue. Thanks for providing such awesome program :)
=> Fix [Error 22] under Windows reading .editorconfig

.editorconfig, .travis.yml, README.md, isort/main.py, setup.py, tox.ini
These changes enable any user that installs `isort` to check his source
code from setup.py with the command `python setup.py isort`
I also checked isort package code with his command in tox and travis.
Acknowledgements: this is mostly inspired by flake8 setuptools integration,
see [flake8 doc](http://flake8.readthedocs.org/en/2.2.3/setuptools.html)
=>  Add Setuptools integration issue #261

isort/isort.py, isort/main.py
It wasn't obvious to me that `__init__.py` files were being skipped.  I see that -vb would print each one, but that is also not default.  I think default-skip should at least be visible with a summary line.
$ PYTHONPATH=/Users/jdunck/open-source/isort isort -rc common/
Skipped 11 files
=> Print the number of skipped files, if any

isort/isort.py, runtests.py, test_isort.py
Hi Timothy!
Thanks for creating isort! It's quite useful.
I ran into a bug when using isort to lint a file that contained an import in which the split token "import" appeared in a module's name. This resulted in the module's name being split into non-sense strings.
e.g.
```python
from mycompany.model.size_value_array_import_func import (
get_size_value_array_import_func_jobs,
)
```
... was split into ...
```python
[u'mycompany.model.size_value_array_', u'_func ', u' get_size_value_array_', u'_func_jobs']
```
I have patched the isort _wrap() function to prevent this from happening. I ensured that all tests passed after my patch was introduced, and I added an additional test to ensure that line splitting is word boundary aware.
All the best,
-Patrick
=> Fix Import Line Splitting Bug

.gitignore, README.md, isort/__init__.py, isort/isort.py, isort/main.py, isort/settings.py, setup.cfg, test_isort.py
Users can now define their own sections and ordering. For example
import_heading_stdlib = Standard Library
import_heading_thirdparty = Third Party
import_heading_firstparty = First Party
import_heading_django = Django
import_heading_pandas = Pandas
known_django = django
known_pandas = pandas,numpy
known_first_party = p24,p24.imports._VERSION
sections = FUTURE,STDLIB,DJANGO,THIRDPARTY,PANDAS,FIRSTPARTY,LOCALFOLDER
would create two new sections with the specified known modules.
import os
import p24.imports._argparse as argparse
import p24.imports._subprocess as subprocess
import sys
from django.conf import settings
from django.db import models
from bottle import Bottle, redirect, response, run
import numpy as np
import pandas as pd
import p24.imports._VERSION as VERSION
import …
=> Custom section support

.gitignore, isort/isort.py, test_isort.py
`isort` doesn't handle different source code encodings very well - if you make a python file like 
``` 
s = u'ã'
```
Where the file is saved in latin1 encoding, it is a perfectly valid python module in both python 2 and python 3.  But unfortunately `isort`will raise an unhandled exception, because it assumes files are saved in utf8 coding.  Furthermore, `isort` will currently save all files as utf-8 encoding, *but not change the coding declaration of the source*, which is dangerous.  We should either respect the original encoding, or rewrite the coding declaration to mention that the new file is saved in utf-8.
=> Respect the coding declaration 

README.rst, setup.py
Resolves #301 . Looks a bit better to me since `ini`/`python`/`bash` highlighting is specified :)
You can preview on https://github.com/adamchainz/isort/tree/readme_rst . The command `python setup.py check --restructuredtext` passes which implies it will look fine when uploaded to PyPI.
=> Convert README to rst

isort/isort.py, isort/main.py, isort/settings.py
This adds support for skipping based on globs. There are more details in the original issue #292 . 
Tests need to be added. I didn't see any file skipping tests in test_isort.py . What would be the proper way to add those tests, something similar to  test_other_file_encodings()?
=> Add globbing support, fixes timothycrosley/isort#292

isort/isort.py
Particularly useful for situations where `not_skip=__init__.py` and `skip=my/module/__init__.py`
=> Allow files that are skipped to be non-absolute paths

isort/settings.py, test_isort.py
Fixed custom sections parsing from config file (unicode string -> list).
Now isort works more correct (especially with pre-defined modules in settings).
=> Fixed custom sections parsing from config file (unicode string -> list).

isort/isort.py, test_isort.py
git hooks provide both file_path and file_contents. Previously,
should_skip only checked if file_path was provided without
file_contents. This introduced a situation where the isort git hook
would fail on files that isort wouldn't touch.
Related PR: https://github.com/timothycrosley/isort/pull/218
=> skip files even when file_contents is provided

isort/isort.py
Difflib in py3.5 checks the variable types passed in to unified_diff -
as such it would break saying they aren't strings. Previous Python
versions would just call str() on them rather than checking. This just
adds the str() check and will subsequently fix the issue and still work
on previous Python versions.
=> Fix compatibility with Python 3.5

isort/isort.py
Allows sorting by module within sections like:
```python
import a
from b import c
import d
```
This is to support how my employer does it.
=> Allow imports to be sorted by module, independant of import_type

isort/pylama_isort.py
[.....]
Run isort {}
Traceback (most recent call last):
File "/.../lib/python3.4/site-packages/pylama/core.py", line 65, in run
select=params.get("select", set()), params=lparams):
TypeError: 'NoneType' object is not iterable
=> Pylama expects a iterable to be returned.

isort/settings.py
These default settings are required because `_update_with_config_file`
convert the value from config file to an existing value type. The existing
value type is determined from the value of the `access_key` in the
`default` dict.
=> Add default value to config settings

isort/main.py
Kept --force_single_line_imports as a hidden option for backwards compat
Fixes #367
=> Make naming of --force-single-line-imports consistent with other params

isort/isort.py
The list of hardcoded versions is already out of date.
Apart from that we might also assume that `VIRTUAL_ENV` should be in
`sys.path` already, and remove this completely?!
=> Use `glob` to add VIRTUAL_ENV to paths

isort/isort.py
If you `pip install -e` a requirement it is considered to be first-party
always.
This makes sense for the typical `pip install -e .`, but not when
installing requirements editable through Git, where it appears to be
useful in case you want to hack on it.
I've tried adding the following to `place_module`, but it also catches
the `pip install -e .` case.  This could then be worked around by adding
it to `known_first_party`, but then it might also be an option to have a
mode where only explicitly defined packages are considered to be
first-party?!
```
elif os.path.exists(os.path.join(prefix, os.path.basename(prefix).replace('-', '_') + '.egg-info')):
return self.sections.THIRDPARTY
```
With this change the following config will work as expected:
known_first_party = myproject
default_section …
=> Use default_section instead of FIRSTPARTY as fallback for existing paths

isort/isort.py
This is helpful for running [pre-commit](https://github.com/pre-commit/pre-commit) hooks since they run in their own virtual environment where `isort` fails to correctly infer whether a package is third-party or not, since no packages are installed there.
=> Allow specifying virtual env directory

isort/isort.py
This fixes the following error with `isort --diff -`:
Traceback (most recent call last):
File "…/pyenv/project/bin/isort", line 9, in <module>
load_entry_point('isort', 'console_scripts', 'isort')()
File "…/isort/isort/main.py", line 239, in main
SortImports(file_contents=sys.stdin.read(), write_to_stdout=True, **arguments)
File "…/isort/isort/isort.py", line 170, in __init__
self._show_diff(file_contents)
File "…/isort/isort/isort.py", line 194, in _show_diff
fromfiledate=str(datetime.fromtimestamp(os.path.getmtime(self.file_path))),
File "…/pyenv/project/lib/python3.5/genericpath.py", line 55, in getmtime
return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: ''
=> Fix `--diff` with stdin

isort/main.py, isort/settings.py
This would occur when not_skip is applied to `__init__.py`, and skip has a file like `some/module/__init__.py`. This meant that all `__init__.py` files were skipped
=> Fix 'not_skip' not ignoring working, when there is a more specific filepath in the skip list

isort/isort.py, test_isort.py
Addresses https://github.com/timothycrosley/isort/issues/399
This uses `fnmatch` to provide globbing to the `forced_separate` options. This allows things like "all Django models", for example, to be separated into another section.
The current limitation of this is that it does not apply to local imports. Unfortunately, adding this looks like much more work, so I'm inclined to leave the change at this.
=> Add support for globbing in forced_separate

isort/isort.py, test_isort.py
Raised in https://github.com/timothycrosley/isort/issues/364
The separate code for --force-alphabetical-sort has been removed and
a boolean flag added to handle sorting with or without case in the
_module_key function (which handles the sorting).
Note this commit alters these 2 tests:
test_alphabetic_sorting_no_newlines, test_alphabetic_sorting
This results in the lone imports being moved to the top of the file.
I think this is better as it means the force_alphabetical_sort tests
now behave similarly to the other tests in the file.
Please advise if it is ok to change the tests like this. 
The big red commit in isort.py is because lines 444 -> 468 were removed and the 
if statement was removed
=> Fix multiline sorting with force-alphabetical-sort

test_isort.py
If running `isort -a "from __future__ import unicode_literals" file.py`, where `file.py` consists of a function like:
```python
def foo():
""" Single line triple quoted doctring """
pass
```
`isort` incorrectly adds the import like so:
```python
def foo():
""" Single line triple quoted doctring """
from __future__ import unicode_literals
pass
```
Which is a syntax error. I've written a failing test for this case in this PR, although I am unsure where to start looking to fix it.
=> Imports added incorrectly in function with docstring

isort/isort.py, test_isort.py
Fix single line imports for hanging indents. 
Changed 1 test for the above.
Fixes:
https://github.com/timothycrosley/isort/issues/365
I added an if on line 429 to say "If line is too long & we have at least 1 import & we are using a hanging indent wrap mode" -> then we format the line. 
It looks ok, but please check it and point out if I have made a mistake.
=> Fix single line imports for hanging indents. 

isort/isort.py, test_isort.py
As mentioned in https://github.com/timothycrosley/isort/issues/425
This fixes hanging imports being removed by isort.
Code was missing a whitespace when glueing the import line together
=> Fix hanging imports being removed

setup.py
It's unnecessary as pip downloads from PyPI.
=> setup.py - remove download_url

isort/main.py
```
[settings]
indent='    '
line_length=200
lines_after_imports=2
skip=migrations
```
```
#!/bin/bash
isort -rc -sp .isort.cfg .
```
Command above doesn't work.
Below show the commands which work and not work.
```
#!/bin/bash
isort -rc .  # work
isort -rc -sp . .  # work
isort -rc -sp .isort.cfg .  # not work
isort -rc -sp ./.isort.cfg .  # work
```
```
-sp SETTINGS_PATH, --settings-path SETTINGS_PATH
Explicitly set the settings path instead of auto
determining based on file location.
``` 
As description in ``isort -h``. You maybe just want user to use PATH of ``.isort.cfg`` as argument.
But once user use command ``isort -rc -sp .isort.cfg .``. He will feel this is a bug.
And spend a lot of time to search for the right usage.
=> fix settings in .isort.cfg not work

isort/main.py
Expose `virtual_env` config on the command line. This is helpful e.g. when running `isort` as an external tool from PyCharm, which doesn't seem to let you specify any environment variables like `VIRTUAL_ENV`.
=> Add --virtual-env command line switch

isort/isort.py
As you can nicely see in the diff, the condition
``` python
if show_diff or self.config.get('show_diff', False) is True:
```
exists twice and results in printing the diff twice if there are any differences. Remove one of them.
=> Show diff only once

isort/isort.py, test_isort.py
For example:
1. multi_line_output = 0, 1 or 2; include_trailing_comma = true
from third_party import (
long_name_of_the_library,)
2. multi_line_output = 3 or 5; include_trailing_comma = true
from third_party import (
long_name_of_the_library,
)
3. multi_line_output = 0, 1 or 2; include_trailing_comma = false
from third_party import (
long_name_of_the_library)
4. multi_line_output = 3 or 5; include_trailing_comma = false
from third_party import (
long_name_of_the_library
)
=> Fix issue #445: Applying 'use_parentheses' should depend on 'multi_line_output' and 'include_trailing_comma'

isort/isort.py
This makes `stdout` capturable by using [this hack](http://stackoverflow.com/a/10743550/1160341).
=> Make stdout capturable

isort/isort.py, test_isort.py
This uses `sys.prefix` to decide if a file is from the stdlib instead of relying that `python2` or `python3` appear anywhere on the PATH.
This solves the problem of Python from official distribution installed in a non-standard location or other distributions (such as conda).
I don't know how I can write a test for the actual problem (Python installed in a non-standard location) because both AppVeyor and Travis have Python installed in a standard location. :sweat: 
Fix #464
=> Place modules found in sys.prefix/lib in stdlib section

isort/isort.py, test_isort.py
Fix issue reported here: https://github.com/timothycrosley/isort/issues/460
Multiline comments were being moved into the wrong place.
Test added.
***_Please Note**_*
isort.py  line: 865 was changed in commit: f157b06 and I do not see
why the more complex comparison was needed so it has been removed. Please reread the original commit before accepting this merge request.
=> Fix multiline comments being moved

README.rst, isort/settings.py
Fixes issue #487
Thanks to _update_settings_with_config this was a one line addition.
Added mention in README.rst (and fixed nearby double "the" typo). I
didn't see specific tests for finding correct config file.
=> Support Configuration in tox.ini

isort/isort.py, test_isort.py
With this changes `isort` should properly add default two blank lines after import section when the next line starts with `async def` #453 .
=> Fix smart lines after import section for async functions

isort/isort.py, isort/main.py, isort/settings.py, test_isort.py
This switches --force-grid-wrap to a configurable int (#476)
Almost fully backwards compatible except one small case: when -fgw is the last arg specified before files. That's a simple fix for anyone running into it after seeing the new --help text.
More importantly this doesn't impact config files, which I'd think is more relied upon than command line args.
=> switch force-grid-wrap to an integer value (#476)

isort/isort.py, test_isort.py
On a 1300 file project at my company, this change reduces the run-time from 11 minutes down to 5 seconds, a 130x improvement.
=> Use a copy of sys.path

isort/isort.py
sorted() can take any iterable. So simply pass the iterable instead of
first coercing to a list. Inspired by Lennart Regebro's PyCon 2017
presentation "Prehistoric Patterns in Python". Available at:
https://www.youtube.com/watch?v=V5-JH23Vk0I
=> Remove unnecessary list coercion

CHANGELOG.md
It is a bit unusual and unconventional to order a CHANGELOG with the
most recent release at the bottom. Due to this, it is easy for a new
user to incorrectly read version 4.0.0 as the latest release. Bring
CHANGELOG into more typical ordering to reduce confusion.
Follows suggestions from "Keep a CHANGELOG": http://keepachangelog.com/.
> List releases in reverse-chronological order (newest on top).
=> Reorder CHANGELOG to be in reverse chronological order

isort/main.py
When using CLI action store_true or store_false, the opposite value is
always the implied default. No need to specify it.
From https://docs.python.org/3/library/argparse.html#action
> 'store_true' and 'store_false' - These are special cases of
> 'store_const' used for storing the values True and False respectively.
> In addition, they create default values of False and True
> respectively.
=> Remove unnecessary CLI arg defaults

isort/isort.py, isort/main.py
Now simply use dict indexing instead. Uses simpler and more conventional Python syntax for directly accessing a value in a dict. A small micro optimization for keys known to exist as they're specified in
`isort.settings.default`. Will also more easily expose typos and programming errors as an incorrect key now results in a `KeyError` instead of silently falling back to a default value.
There remain a few `config.get()` calls as changing them causes test failures. I wasn't sure which case they fall under:
* Truly optional values that may not exists, dict.get() is the best choice here
* Should be specified in settings.default
* Exposing an unnoticed error
=> Remove unnecessary dict.get() calls when retrieving config values

CHANGELOG.md, isort/isort.py, isort/main.py, isort/settings.py, test_isort.py
Restores original behavior of enforcing whitespace by default. The
behavior was broken in a backwards incompatible way starting with commit
5f6d4bd45e0fa8e3b6b2bea81d3eb7368ee312c3. Ignoring whitespace is now
opt-in instead of opt-out.
Ignoring whitespace by default has lead to a number of confused users,
myself included. CI would seemingly pass but isort --apply would still
make changes. Some users have asked for the original behavior be
restored and the new feature be behind a CLI argument.
Refs #378
Fixes #423
Fixes #481
=> Replaced the --enforce-whitespace option with --ignore-whitespace

MANIFEST.in
Includes the tests for packagers. Also include LICENSE and CHANGELOG for
library users.
Fixes #463
=> Add MANIFEST.in to include additional files in releases

isort/__init__.py, isort/isort.py, isort/pie_slice.py, isort/settings.py, runtests.py, setup.cfg, test_isort.py, tox.ini
**1) Fix more lint warnings reported by flake8:**
Fixes:
```
test_isort.py:33:1: F403 'from isort.pie_slice import *' used; unable to detect undefined names
test_isort.py:33:1: F401 'isort.pie_slice.*' imported but unused
test_isort.py:366:1: E302 expected 2 blank lines, found 1
test_isort.py:891:51: E261 at least two spaces before inline comment
test_isort.py:1340:1: E303 too many blank lines (3)
test_isort.py:1792:1: E302 expected 2 blank lines, found 1
test_isort.py:2038:5: E303 too many blank lines (2)
isort/isort.py:165:114: E502 the backslash is redundant between brackets
isort/isort.py:413:13: E303 too many blank lines (2)
isort/isort.py:563:24: E713 test for membership should be 'not in'
isort/isort.py:726:16: E713 test for membership should be 'not in'
isort/isort.py:831:72: E713 …
```
=> Increase flake8 coverage

README.rst, isort/natural.py, isort/pie_slice.py, tox.ini
Fixed all URLs where https is supported. Dropped the auto-generated, boilerplate from `tox.ini` instead of editing the URL.
=> Prefer https URLs over http in docs and comments

isort/isort.py, test_isort.py
We already do this when the configuration specifies skipping a file, but not when the file is empty or the _file_ specifies skipping.
The "skipped" flag is relied upon by some tooling (I'm not sure if it constitutes public API, but it should be fixed anyway), and that tooling is failing in these cases.
=> Set skipped=True when we skip the file

isort/isort.py, test_isort.py
Mac OS X works in a case-insensitive manner when checking path existence. This PR applies the same logic for Mac OS X installations as isort has for windows
=> Fix case-sensitive path existence check in Mac OS X

isort/isort.py, isort/main.py, isort/settings.py, test_isort.py
I would like to propose a new option for optionally skip splitting by empty lines for some sections.
In our internal code style we don't split local imports and first party imports because they are parts of the same project and this will add additional 6th level of imports when we already have 5: futures,stdlib,django,thirdparty,firstparty+local
Also, it would help to solve #447
=> Add no_lines_before option to let sections not be split from previous

isort/main.py
While allowed by most tools, it is very unconventional.
=> Remove unconventional space after shebang

isort/isort.py, test_isort.py
Hi!
I've found an unexpected behavior in earlier introduced `no-lines-before` option. Suppose we have STDLIB and local imports. We obviously won't want to merge them into one group. So I think it has much more sense to merge only neighbor sections, which might be configured via `sections` or `forced_separate` options
=> merge only neighbour sections in case of enabled no_lines_before option

isort/isort.py, isort/main.py
While configuring isort as a pre-commit hook, I had some issue because I was misusing the command (I was using path with tilde to --virtual-env i.e: ~/dev/env) and it took me some debugging to find out why it wasn't sorting my imports correctly. In fact when providing a virtual_env directory that does not exist, it silently ignores it but this has a significant impact on the import sorting.
So I ended up implementing the following:
- Use abspath for virtual_env (to make it consistent with settings_path)
- print warning in case virtual_env or settings_path directories don't exist
- print 'Fixing {filepath}' whenever isort actually overwrites a file (I believe it is a good practice for such library and it's very helpful when used as a hook)
=> minor things to improve usability 

isort/isort.py
Fix a bug where variables are mistaken for function definitions. 
This fixes a bug wherein a variable definition prefixed ``default_`` would
be confused with a ``def foo()``, because they both start with ``def``.
(Whether it's a function def or a variable changes the
expected default lines-after-imports behaviour. Noticed this when
isort and yapf began clashing over these cases.)
=> Fix 'lines_after_imports' detection

.env
Support for Python 3.3 was removed in commit 9ac80c514fc26ebed0bec0e8d67ae6b0b4e50679.
=> Remove additional references to Python 3.3

isort/isort.py, test_isort.py
Prior to this change, the smart newline code was doing the wrong thing when
faced with code like this:
```
from x import y
something = """
test"""
class Blah():
pass
```
The smart new lines code attempts to find the first construct after the import
block, and uses the `_skip_line` function to determine where that construct
starts.  However, `_skip_line` seems to incorrectly assume that a line ending
with `"""` is a docstring.   It then goes on to treat `class Blah` as the first
construct, and adds 2 new lines after imports instead of the 1 that should be
chosen.
I've fixed this by updating `_skip_lines` to stop iterating over the characters
of a line if it finds something that is neither whitespace, the start of a
string or a comment.
=> Smart newlines no longer skips multi-line string assignments

isort/isort.py, test_isort.py
Prior to this change, isort was always adding 1 to the current line length when
determining whether or not the current line had got too long when outputting a
vertical grid.
- For imports that are not last, this is fine.  We need to account for the comma
after the import.
- For the final import in vertical grid mode this is also fine.  We need to
account for the closing `)`.
- For the final import in the grouped vertical grid we put the closing ) on the
next line, so adding 1 to the line length causes isort to add un-neccesary
line breaks when the final import would only just fit onto the line by one
character.
For example, with a line length of 20:
```
from x import (
abcd, efgh, ijkl
)
```
will end up reformatted as
```
from x import (
abcd, efgh,
ijkl
)
```
This is causing problems for …
=> Don't add un-neccesary line break in grouped vertical grid.

isort/isort.py
I chose to replace " .import" with " . import" because without the initial space, the change might create an error when ".import" was intentional, for example:
from CoolPackage.import ExcellentClass
=> Fix 613 Addresses error recognizing "from .import foo"

isort/isort.py, test_isort.py
also added a simplified test of import being a module or package.
fixing #594.
=> added a test for imports created at load time, such as six.moves.

isort/isort.py, test_isort.py
=> Handle parenthetically enclosed imports starting after an escaped line

isort/main.py, test_isort.py
If a file does not exist (e.g. a symlink to a file that does not exist yet), don't attempt to sort it.
=> Don't attempt to process files we can't open

isort/isort.py
At least on some occasions, setting `newline` to whatever the line endings currently are can cause Python to replace the `\n`s with whatever you pass in, causing lines to be encoded twice. This leads to CRLF files containing `\r\r\n` sequences in place of `\r\n`.
Fixes issue #671.
=> Do not apply line endings twice. (#671)

setup.cfg, setup.py
The "futures" package need only be installed on Python 2. To specify a conditional dependency, setuptools, pip, and wheel support "environment markers". Use this mechanism instead of adding install time logic to the setup.py file.
Allows restoring universal wheel support, allowing a single wheel for all version of Python.
For additional details on wheel support for environment markers, see the documentation at:
https://wheel.readthedocs.io/en/stable/index.html#defining-conditional-dependencies
> Defining conditional dependencies
>
> In wheel, the only way to have conditional dependencies (that might only be needed on certain platforms) is to use environment markers as defined by PEP 426.
>
> ...
>
> As of setuptools 36.2.1, you can pass extras as part of install_requires. The above …
=> Use environment markers to define Python2 specific dependencies

isort/isort.py
The dictionary comprehension syntax is available on all supported Python versions. Dictionary comprehension is modern Python syntax and is always faster than the `dict()` constructor, e.g.:
```
$ python3 -m timeit 'dict((a, a) for a in range(20))'
100000 loops, best of 3: 2.16 usec per loop
$ python3 -m timeit '{a: a for a in range(20)}'
1000000 loops, best of 3: 0.953 usec per loop
```
=> Use dict comprehension instead of a dict() constructor

tox.ini
isort is not a dependency to install & run flake8. Use the `skip_install` configuration option for a slightly faster build.
For details on skip_install, see:
https://tox.readthedocs.io/en/latest/config.html#confval-skip_install=BOOL
=> Skip installing isort when running the "lint" tox environment

isort/settings.py
Editorconfig allows the word `tab` to be used for `indent_size`, which
will result in it using the value from `tab_width`. However, this was
causing a `ValueError` because this condition was not handled.
=> Handle non-int `indent_size` in .editorconfig

README.rst
According to the code, the default line length is 79: https://github.com/timothycrosley/isort/blob/7e2fb3b21b4b588dc7a62ac65693781ae39e8a98/isort/settings.py#L52
=> Update line length docs to match the code

isort/isort.py
This fixes current behavior where tools that accept output piped from isort sometimes get empty files, which can cause files to be deleted instead of left alone.
=> Pass output to stdout even on skipped files

isort/isort.py, test_isort.py
Configured known patterns ending with a path separator gets expanded and replaced with sub packages. Probably solves a few different scenarios like grouping section for packages under path, pointing out first party folder etc.
**Related issues:** (?)
Fixes #347 
Fixes #692
**Example:**
Lets say the repo has a `src` folder with a few parallel packages.
``` sh
$ find .
./src
./src/foo
./src/foo/__init__.py
./src/foo/bar.py
./src/ham
./src/ham/__init__.py
./src/ham/spam.py
```
Instead of manually adding `foo`, `ham`, etc. as first party modules, the following *pattern* ...
``` sh
$ isort -p src/ foo/bar.py
```
... gets automatically expanded, as if you would have ...
``` sh
$ isort -p foo -p ham foo/bar.py
```
=> Support path patterns for known sections to find sub packages

isort/__main__.py, isort/pie_slice.py
isort has a Python3 compatibility module that, among other things, changes the Python environment when imported. These changes aren't restricted to the module importing though; they apply to all code running in the environment.
This is fine when executing isort as a command. However, this leads to weird issues when isort is used as a library, e.g. pytest-isort, because once loaded, it changes the behaviour of Python from that point onwards.
This led to an interesting issue where, depending on if pytest-isort (which imports isort) is installed, UnicodeDecodeErrors are or aren't raised on Python 2.7 due to the sys.setdefaultencoding call. See https://github.com/moccu/pytest-isort/issues/10
I don't think isort should be changing the Python environment through the simple act of importing the …
=> Don't change Python2 str encoding on import

.gitignore, README.rst, isort/finders.py, isort/isort.py, isort/utils.py, setup.py, test_isort.py, tox.ini
1. Split `place_module` to separated classes named "finders". It's make developing and extending easier.
1. Move some operations from "parse_module" stage to "init".
1. Add finder for Pipfile via [requirementslib](https://github.com/sarugaku/requirementslib/) (part of [pipenv](https://github.com/pypa/pipenv/))
1. Add finder for requirements.txt via pip.
1. Both finders (requirements and pipfile) uses [pipreqs](https://github.com/bndr/pipreqs/) for converting PyPI package name to module name.
Fix #459
=> requirements.txt and Pipfile support

.travis.yml
tox already reads the TOXENV environment variable. No need to re-specify
as a command line argument. For details, see:
https://tox.readthedocs.io/en/latest/config.html#confval-envlist=CSV
=> Remove unnecessary tox -e argument

isort/pie_slice.py, tox.ini
This is a repeat of #732 which I closed but could not reopen.
This is to assist #716 to migrate testing from Python 3.6 --> 3.7.
=> Tox:  Perform lint test on Python 3

isort/isort.py, test_isort.py
When the very long line is met isort should wrap import into one of
multi line outputs. Black says that vertical hanging indent should be
choosen. An for most cases it works correctly. But when only one
import is on the list there is some difference.
Black suggests that there shouldn't be a trailing comma which isort is
giving.
=> Make formatting import compatible with black check

README.rst, isort/settings.py
I wasn't sure if the section was explicitly "isort" or something else. I added styling to make that obvious and added support for using "tool:isort" as the section name.
=> explicitly state the section is "isort" and add support for "tool:isort"

isort/finders.py, tox.ini
- Fix Pipfile test to correctly return requirement names
- Drop `basepython` from lint environment so lint can run in any environment
Travis is green again 🎉
=> Fix test and Travis failures

isort/main.py
Executing isort as script is handled by using either `python -m isort` or the main entry point installed by setuptools. Individual files need not be set as executable.
=> Remove shebang from isort/main.py

isort/settings.py
dict.update() can handle the same arguments as dict().
=> Remove unnecessary coerce to dict

.travis.yml
=> Test against latest PyPy on Travis

isort/settings.py
Fixes issue #737 with using Unix-style paths in the skip list when running isort on Windows.
Tested via the settings used on pandas.
=> Fix Windows path issue

isort/main.py, isort/settings.py, test_isort.py
This PR makes sure isort won't wander into directories where it shouldn't. By @jdufresne's suggestion, this list is based on that of [Black's](https://github.com/ambv/black/blob/024c9cab55da7bd3236fd88759c9735d6149b464/black.py#L53-L55), with my addition of "lib/pythonX.X", which appears within venvs/site-packages/etc., but should never appear elsewhere.
This behavior can be disabled with the `--unsafe` switch.
Fixes #759
=> Refuse to work in system/.tox/venv/... directories by default

README.rst, isort/isort.py, test_isort.py
This addresses my feature request in https://github.com/timothycrosley/isort/issues/785 - essentially it allows one to sort by line length only for some sections and alphabetically for others. My preferred style is to sort the standard library imports by line length and other sections alphabetically.
To sort only one section by line length, this uses the same syntax as for the headings:
```
length_sort_stdlib = True
```
=> Add support for opting in to line length sorting for only specific sections

isort/main.py, test_isort.py
* The main.py module had been left mostly untested as far as coverage showed, so this PR adds a test to see that the main bits in there don't smoke an awful lot when plugged in.
* There was needless duplication in the multiprocessing code, which is now neatly DRYed out.  
In addition, use of `concurrent.futures` (3.2+) was replaced with `multiprocessing` (2.6+). (Not that it matters an awful lot with #782 pending, but still, it felt cleaner like this.)
=> Test coverage improvements

README.rst, isort/hooks.py
With reference to #770, this adds an option to the ``git_hook`` function to allow it to not only display warnings when sources are unsorted, but also fix the sources.
This addition is off by default, so no existing usage will be affected.
I would still argue that ``modify=True`` should be the default, to be in line with the tagline "_isort your python imports for you so you don't have to_". This way, the user doesn't even have to do the sorting, just simply re-staging the files. But I guess this will come at a cost of breaking backwards compatability (hence the per now default of ``modify=False``).
=> Add option for git_hook to modify files

isort/isort.py, test_isort.py
Commit https://github.com/timothycrosley/isort/commit/75b354995028c66a801c8c0e60f817b60fc64e8e removed commas if there was only one import, ostensibly to conform to Black, but currently Black behavior is such
```
MBP-jpaige% cat test.py
from some.very.lengthy.example.library.that.goes.too.far.subdomain1 import (
AnObnoxiouslyLongClassName1,
)
from some.very.lengthy.example.library.that.goes.too.far.subdomain2 import (
AnObnoxiouslyLongClassName2,)
from some.very.lengthy.example.library.that.goes.too.far.subdomain3 import (AnObnoxiouslyLongClassName3,)
from some.very.lengthy.example.library.that.goes.too.far.subdomain4 import (AnObnoxiouslyLongClassName4,
)
from some.very.lengthy.example.library.that.goes.too.far.subdomain5 import AnObnoxiouslyLongClassName5
from …
```
=> Keep trailing comma even for a single from import. Issue 831

isort/isort.py, test_isort.py
Expected behavior is now that all isort:skip and NOQA imports will be moved to bottom, unsorted.
=> Added NOQA to lines to be skipped 

isort/finders.py
Fixes https://github.com/timothycrosley/isort/issues/848.
On Django source code:
isort==4.3.4:
```
$ time isort --quiet --recursive --diff . > isort.out 
5.83user 0.10system 0:05.94elapsed 99%CPU (0avgtext+0avgdata 27760maxresident)k
```
master with those finders enabled:
```
$ time isort --quiet --recursive --diff . > isort.out 
25.82user 2.51system 0:28.43elapsed 99%CPU (0avgtext+0avgdata 51260maxresident)k
```
with those disabled:
```
$ time isort --quiet --recursive --diff . > isort.out 
6.87user 0.13system 0:07.02elapsed 99%CPU (0avgtext+0avgdata 49848maxresident)k
```
20% slowdown from a 4.3.4. should be tolerable, for now, I guess. 
`RequirementsFinder` is the slowest, disabling it alone gives me about 15sec boost on this codebase. In the future, results from finders should …
=> Disable requirements based finders

isort/finders.py
This caches the result of the function for future invocations with the same
input, which can massively speed up future invocations if they have the same
input as previous calls.
In the case of this function this happens a lot, and each invocation is quite
expensive as the requirements file is parsed every time.
This gives a quite significant performance boost. I've tried running `isort`
with and without this patch on two different applications on Python 3.7.2 and
one one application the run time drops from 12.67 seconds to 1.3 seconds and
on the other it drops from 28.29 seconds to 2.1 seconds.
This optimisation is similiar to the one which was done for the 4.3.x branch
here: https://github.com/timothycrosley/isort/pull/856.
=> Add LRU cache to RequirementsFinder._get_names

isort/settings.py
Allows users to supply something like `multi-line=VERTICAL_HANGING_INDENT` rather than `multi-line=3` on the command line (and in `.isort.cfg`). Happy to add tests if required, just struggled a little to find where they might go inside `test_isort.py`.
=> allow named multi_line_import arguments

test_isort.py
Restore `chdir` after tests.
This is relevant for when pytest-cov would display coverage in the end,
and would use absolute paths due to this.
=> tests: fix default_settings_path

test_isort.py
This also failed for me with "future" being installed.
Not sure if it makes sense to keep it in the first place, since isort
appears to require py34 now.
Ref: https://github.com/timothycrosley/isort/issues/479#issuecomment-316235116
=> Fix test_inconsistent_behavior_in_python_2_and_3_issue_479

isort/settings.py, test_isort.py
Currently `isort` crashes trying to parse `multi_line_output` from a config file due to the fact that `WrapModes(str)` is not a valid `str -> type instance` callable.
=> Fix bug with parsing WrapModes from config file

isort/isort.py, isort/main.py, isort/settings.py, isort/utils.py
I want to start working on a https://github.com/timothycrosley/isort/issues/818, but decided to refactor the project a bit to make it a little more extensible. 
Diff ended up being too big, and current develop won't merge cleanly in new branch at all, so I cherry-picked part of it which is mergeable.
And in general, what do you think about it? Is it a good idea? I want to split big `SortImports` object into a number of smaller ones to
1. Reuse parsing logic for function / if-block scoped imports.
2. Make it a little more maintainable, my PyCharm can't even index `isort.py` properly, it's too big and complex.
=> Split SortImports class into smaller classes, part 1

isort/finders.py
This ensures we don't get confused and incorrectly classify third party
libraries as first party libraries.
Fixes #876.
=> Lookup real path of virtualenv

isort/settings.py
TOML is a typed file format so if you had `multi_line_output = 3` specified in
your `pyproject.toml` file you would get an error like this after the changes
in https://github.com/timothycrosley/isort/pull/860 were merged in:
> TypeError: getattr(): attribute name must be string
This change makes sure the attribute name is a string when passed to `getattr()`
to avoid errors like this going forward.
=> Support integer values for `multi_line_output` from TOML files

isort/isort.py, test_isort.py
The current help for the `--quiet` option says that it enables "extra
quiet output, only errors are outputted".  However, isort still prints
`Fixing spam/eggs.py` messages to stdout.
=> Do not print file names when in the quiet mode

isort/isort.py, isort/main.py
Here is a proposed patch for #842 that works on Python 2 and Python 3.
Tested with a UTF-8 encoded file and a latin-9 encoded file:
```console
$ isort - < test_utf8.py && echo ok
x = 'testé'
ok
$ isort - < test_latin9.py && echo ok
x = 'testé'
ok
```
```console
$ isort test_utf8.py && echo ok
ok
$ isort test_latin9.py && echo ok
ok
```
Also tested with flake8-isort:
```console
$ flake8 --no-isort-config test_utf8.py && echo ok
ok
$ flake8 --no-isort-config test_latin9.py && echo ok
ok
```
=> work on file encoding detection

.pre-commit-hooks.yaml
Helps isort work as a pre-commit hook with [pre-commit](https://pre-commit.com/)
=> Add .pre-commit-hooks.yaml to ensure use with pre-commit

.pre-commit-hooks.yaml
👋 hello, pre-commit maintainer here
A few small things to make this usable elsewhere :)
- `additional_dependencies: []` is the default
- `types: [python]` will limit `isort` to running on python code instead of every file in the repository
=> Update the pre-commit configuration for isort

isort/isort.py
When there is a non-asaii code character in the file, an error will be reported in python2.
=> Fix:  "isort -" will raise UnicodeEncodeError on python2.

isort/settings.py
Resolves #923 
When toml is used for config, and especially with the seed-isort-config pre-commit function, the setting gets set to a list of strings, rather than a comma-separated string. This checks that the value passed is already a list and if so strips each item to be safe, and returns that.
This does not update the type-hints in the signature, as the function isn't really supposed to expect a string, but it's just a safeguard in case.
=> Fix list passed from toml settings

isort/finders.py, setup.py, test_isort.py
Fixes #924.
Also removes some (seemingly?) unnecessary `@pytest.mark.skipif` decorators that were preventing the relevant tests from being run.
=> Use pip-api instead of importing pip

isort/compat.py, isort/isort.py, isort/natural.py, isort/settings.py, setup.cfg
1. `# type: ignore` correspond to mypy bugs.
2. Disabled `strict_optional` for tests because of lots of false positives. 
2. Disabled it for `isort/isort.py` because logic is too involved for me now to fix it fast. After parso move, there'll be no need for it at all.
=> Add strict_optional = True for some files

isort/isort.py, test_isort.py
Fix for #957.
```
from package import module as very_very_very_very_very_very_very_very_very_very_long_alias
```
becomes
```
from package import (
module as very_very_very_very_very_very_very_very_very_very_long_alias
)
```
This will be the output even if the `module as alias` line is longer than the maximum line length. There is another possibly valid output mixing backslashes and parentheses to attempt to stay below the line length:
```
from package import (
module as \
very_very_very_very_very_very_very_very_very_very_long_alias
)
```
I haven't implemented that here because it's not obviously better and I want to use `isort` in combination with [black](https://github.com/python/black), which does not use backslashes in this case.
=> Fix issue 957

isort/settings.py
Projects frequently have Python and JavaScript coexisting. NPM is the de
facto standard package manager for JavaScript. Ignore third party
packages by default so projects don't need configure this.
=> Add NPM node_modules to default exclusion list

isort/compat.py, setup.cfg
Discovered a typing bug where a Path object was passed to
os.path.relpath(), but Path support was not added until Python 3.6.
https://docs.python.org/3/library/os.path.html#os.path.relpath
> Changed in version 3.6: Accepts a path-like object.
=> Specify targeted Python version to mypy

isort/finders.py, isort/isort.py, setup.cfg
Warns when a function that normally returns a value doesn't. Fixed all
cases discovered by the tool.
=> Enable mypy warn_no_return in mypy for stricter type checking

isort/hooks.py, test_isort.py
Per the Python docs, subprocess.run() is the preferred interface for
running subprocess and replaces the older API (such as
subprocess.check_output())
https://docs.python.org/3/library/subprocess.html
> The recommended approach to invoking subprocesses is to use the run()
> function for all use cases it can handle. For more advanced use cases,
> the underlying Popen interface can be used directly.
>
>
> The run() function was added in Python 3.5; if you need to retain
> compatibility with older versions, see the Older high-level API
> section.
Allows for:
- Return a str from get_output() to decode once instead of every line of
the result.
- Pass command arguments as a list of strings to ensure no possibility
for unescaped shell injection.
=> Simplify subprocess use with high level run API

test_isort.py
Helps move closer to mypy strict mode.
=> Add return type annotations to test_isort.py

isort/finders.py
`_get_files_from_dir()` should return an iterator, so use `yield from` syntax rather than returning a list.
Add type hints to `_get_files_from_dir_cached()`. It returns a list.
=> Correct typing of RequirementsFinder

test_isort.py, tox.ini
flake8-bugbear is a plugin for flake8 that can find likely bugs and
design problems. It contains warnings that don't belong in pyflakes and
pycodestyle.
Introduced as this tool is recommended by HOPE-8.
=> Add flake8-bugbear to tox.ini lint target

isort/settings.py
`_abspaths()` returns a new list object. There is no need to create a new list a 2nd time.
=> Remove redundant coerce to list

test_isort.py
Black has a bug such that strings that were previously multiple lines
sometimes end up as adjacent strings on one line. See:
https://github.com/psf/black/issues/26
=> Combine adjacent strings into one string

.travis.yml, tox.ini
* Test on Python 3.8 beta, to help the beta before 3.8.0 is out, and also confirm isort tests pass on 3.8
* Update PyPy3 from:
```
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901]
```
to:
```
Python 3.6.1 (784b254d6699, Apr 14 2019, 10:22:42)
[PyPy 7.1.1-beta0 with GCC 6.2.0 20160901]
```
* And Xenial is now the default on Travis
=> CI: Test on Python 3.8 and upgraded PyPy3

isort/isort.py, test_isort.py
With both force_single_line and sort_within_sections enabled, modules
are not reliably sorted alphabetically; instead, all imports that
would be combined if force_single_line were false are instead grouped
together, even if another import should (lexicographically) be
somewhere in their midst. The new test case provides a concrete
example.
Also makes a small regex performance enhancement by precompiling
regexes used when force_single_line=True
=> Fix bad sort with force_single_line and sort_within_sections

isort/compat.py, test_isort.py
* Use the regexp from the PEP
* Fix a bug that also checked the third line for coding
Closes #1027
=> Coding detection closer to PEP 263

.travis.yml, pyproject.toml
Python 3.8.0 was released yesterday, so declare support for it.
* https://discuss.python.org/t/python-3-8-0-is-now-available/2478
~Travis CI doesn't yet have 3.8.0 final, but they do have `3.8-dev` which currently points to the release candidate, so is pretty close to the 3.8.0 release, and isort is tested against `3.8-dev`.~
Edit: Travis have _just_ added `3.8`! :)
Here's the Travis tracking issue:
* https://travis-ci.community/t/add-python-3-8-support/5463
AppVeyor will have support in their next images update: https://github.com/appveyor/ci/issues/3142.
=> Declare support for Python 3.8

isort/finders.py, tests/test_isort.py
Thanks for considering my pull request!
This addresses https://github.com/timothycrosley/isort/issues/1051.
In PR https://github.com/timothycrosley/isort/pull/813 earlier this year, I tried to solve a problem with loading compiled extensions by populating an `ext_suffix` instance variable. While my solution worked for OS X and Linux, it unfortunately didn’t work for Windows, where compiled libraries will end with `.pyd` or with an architecture string and `.pyd`.
This PR changes the behavior to use the extension suffixes from Python’s `importlib.machinery` directly.
=> Issue #1051: find extension suffixes from importlib.machinery

.cruft.json, isort/profiles.py, pyproject.toml
Since #1000 was merged to address black compatibility, best include it in the profile.
=> Add ensure_newline_before_comments to black profile

isort/main.py, isort/output.py, isort/profiles.py, isort/settings.py, tests/test_isort.py
=> Fix issue #969: Add support for single line exclusions

isort/wrap_modes.py
This PR addresses #1093 .
Hi @timothycrosley ,
* implemented the desired functionality.
* named `vertical_hanging_indent_bracket`, hopefully it fits the project's nomenclature
* though this new option would fit better after option `3 - Vertical Hanging Indent`, and be assigned number 4, I added it to the END of the `wrap_modules.py` so that it does not break the API functionality with previous versions (tests wont pass otherwise). It is up to you to decided the best procedure for this.
* PR passes the tests
```
pytest
==== 932 passed, 1 skipped, 56 warnings in 21.48s ====
```
After your comments, before merging, I can update the documentation accordingly.
Cheers,
=> Additional vertical multiline option 

isort/main.py
Also adds config option from #1000 to the argument list.
Feel free to disregard, if the args list is getting too out of hand.
=> Add --ensure-newline-before-comments argument

isort/wrap_modes.py, tests/test_isort.py
The first import was directly appended to the statement earlier(probably to prevent extra code for the first coma(',')). Checked the line length on the first import and added a new line if it goes beyond.
=> Fixes #1015

README.md
This PR fixes a config file name on README.
Before: `$XDG_CONFIG_HOME/isort.cfg`
After: `$XDG_CONFIG_HOME/.isort.cfg` (Added a dot)
=> Fix config file name on README

isort/settings.py
Follow-up for #1143.
Fixes another incorrect config file name.
=> Follow-up for #1143

.dockerignore, Dockerfile, docs/contributing/1.-contributing-guide.md
separated dependency installs from isort install in docker which will cache better. Now docker will only download and install external libraries during the first build, unless the lock file is explicitly changed; all subsequent builds will reuse this checkpoint and will only take as long to build as it takes to copy source files.
=> speed up docker build times

.github/workflows/lint.yml, .github/workflows/test.yml
For #1121.
* Add a workflow for linting
* Only runs on `ubuntu-latest` with Python 3.8
* Add a workflow for `poetry run pytest`
* Runs on `ubuntu-18.04`, `ubuntu-16.04`, `macos-latest`
* Maybe a single `ubuntu-latest` would be enough?
* With Python 3.6-3.8
Examples:
* Lint https://github.com/hugovk/isort/runs/436539359?check_suite_focus=true
* Test https://github.com/hugovk/isort/runs/436539366?check_suite_focus=true
Not included:
* Deploy. This could be done with https://github.com/pypa/gh-action-pypi-publish
* Codecov. Tokenless upload is not yet supported, like with Travis. This either needs the token putting as plaintext in the repo (like https://github.com/pytest-dev/pytest/pull/6441), or waiting a bit longer, they're working on it now …
=> Lint and test on GitHub Actions

isort/api.py
isort 4 would overwrite the old file in place, so its permission bits would not be modified.  But as of commit 1920a6c47796bec4ddc2141dbaece6b44a93834e or so, isort instead writes a new file with default permission bits and renames it into place.  So we now need to explicitly copy the permission bits.
Fixes #1194.
=> sort_file: Preserve permission bits

isort/main.py
Looks like the old name was still there.
=> Change sortImports to isort in CLI help

docs/major_releases/introducing_isort_5.md
PS The pencil icon at https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/ leads to a 404 page:
* https://github.com/timothycrosley/isort/edit/master/docs/major_releases/introducing_isort_5.md
Should it link to the `develop` branch?
* https://github.com/timothycrosley/isort/edit/develop/docs/major_releases/introducing_isort_5.md
=> Docs: Introducing isort 5: Typos and consistency

docs/configuration/config_files.md
Noticed this while trying out `isort` with `black` profile.
Congrats on the release! :)
=> Fix a typo in poetry config sample

docs/configuration/options.md, isort/main.py, scripts/build_config_option_docs.py
1. Add example attributes to ConfgOption in `scripts/build_config_option_docs.py`
1. Add temporary example for `known_other`
1. Sort frozen sets in documentation
1. Modify `buid_config_option_docs.py` to output markdown that doesn't offend vscode markdown linter
Address #1262
1. Support for examples in documentation
1. I needed a place to demo the usage of the examples and I was unsure how to integrate it with your current solution
1. frozenset & set defaults should be sorted for easy of reading and to ensure the `build_config_option_docs` is deterministic
1. Linter was marking unneeded leading and trailing whitespace in certain places
1. Determine proper place for storing examples
=> Add support for examples in docs

README.md
Commit 11e2a74f5d379a68edaa064a0aeb70d8bcad9491 changed the line to
remove the '-rc' flag but seems to have accidentally removed the dot
character at the same time.
=> Fix documentation with missing dot '.'

pyproject.toml
Same as timothycrosley/isort#531 which does no longer work, as now
poetry seems to be used for building the packages
=> Add Changelog, docs and tests to source tarball

docs/configuration/profiles.md, isort/profiles.py, tests/test_isort.py
* Fixes: #1271
* It fixed `TypeError: __init__() got an unexpected keyword argument 'not_skip'`
=> Remove not_skip. Fixes: #1271

scripts/build_profile_docs.py
None of the profiles actually contain a description so this is a no-op, but happened to notice.
=> Fix typo in profile doc description build

isort/output.py, tests/test_isort.py
I think these sections are to find the first line after the tail of imports and I think it does not have to parse anymore when the line is in quotes
https://github.com/timothycrosley/isort/blob/develop/isort/output.py#L180-L206
=> Issue #1276: Fix a bug that creates only one line after triple quotes

isort/profiles.py
Fix typo in `plone` profile missing for the setting `lines_after_imports`
=> Fix typo in plone profile

docs/configuration/options.md, scripts/build_config_option_docs.py
Noticed you closed #1262
I feel like my changes in #1268 didn't quite do enough to close #1262. 
These changes make examples a little more scalable as anyone can now just extend `example_mapping` rather than fooling with that messy if statement I wrote before.  However, I left the todo since this probably still doesn't integrate deeply enough into the sources for this to be the final correct solution.
1. Made an example dataclass for easier refactoring later
1. Made example an optional on your ConfigOption class
1. Improved the formatting of examples
* removed duplicate new lines
* fixed CLI if statement
1. Removed duplicate new lines
1. Moved `Not Supported` for cli arguments to be on the same line
* hope this one is ok.
1. I noticed that re-running your doc script …
=> Improve examples in docs

docs/configuration/options.md
The spelling of this configuration option was updated, but the documentation still uses the old spelling.
=> Use correct spelling for use_parentheses

isort/api.py
Hey! If there is a syntax error right now, `isort` will print something like this:
```
/Users/greg.pstrucha/.virtualenvs/bonfire/lib/python3.8/site-packages/isort/api.py:345: UserWarning: {file_path} unable to sort due to existing syntax errors
warn("{file_path} unable to sort due to existing syntax errors")
```
I've noticed we are not formatting strings properly there, let me know if that works!
=> Make sure that warnings are formatting properly

README.md, isort/hooks.py, tests/test_hooks.py
=> Adds lazy option to git hook.

isort/__init__.py, isort/api.py, isort/io.py, isort/main.py, isort/output.py, isort/place.py, scripts/lint.sh, setup.cfg, tests/test_api.py, tests/test_deprecated_finders.py, tests/test_hooks.py, tests/test_importable.py, tests/test_isort.py, tests/test_settings.py, tests/test_setuptools_command.py
Fixes #1311 
- specify flake8 config only in `setup.cfg` - removed passing in the same options in the `lint.sh` scripts as well
- remove `F401` and `F403` from the global ignore list
- added per-file `F401` ignores for `__init__.py` files and per-line `F401` ignores for all other cases
- removed unused import masked by global `F401` ignores
- changed DeepSource ignore comments to `# noqa: F401`, because those work for both flake8 and DeepSource
- added links to black documentation on why we choose to ignore `W503` and `E203` - the only globally ignored rules left
=> Flake8 config cleanup.

docs/contributing/4.-acknowledgements.md, poetry.lock, pyproject.toml, tests/test_hypothesmith.py
Hey @timothycrosley!  I saw https://github.com/Zac-HD/hypothesmith/issues/8 and thought I'd write you a pull request :smile: 
Notable features:
- custom strategy for `Config` objects to explore more weird edge cases
- custom composition of Hypothesmith strategies to boost number of import statements
- custom targeting logic to boost code complexity and number of import statements
Bugs that this can find (albeit with lowish probability):
- `"import A\nimportA\r\n\n"`, `importA` incorrectly treated as an import, unstable whitespace
Once you get it passing, I'd suggest using `while pytest -n=auto --dist=each tests/test_hypothesmith.py ; do : ; done` to soak up some CPU time looking for bugs overnight - if that doesn't find anything, it's unlikely that there's anything the test can find at …
=> Add property-based test with Hypothesmith

isort/settings.py
Invalid value in `.editorconfig` file causes crash of isort.
**Example of invalid `.editorconfig`:**
```
[*]
max_line_length = null
```
isort crashed with error:
```
File "/var/task/python/lib/python3.8/site-packages/isort/settings.py", line 229, in _update_with_config_file
computed_settings['line_length'] = float('inf') if max_line_length == 'off' else int(max_line_length)
ValueError: invalid literal for int() with base 10: 'null'
```
No crash.
**Simple fix:** just check if the `max_line_length` value is correct.
=> Fix max_line_length parsing issue

docs/configuration/options.md, isort/main.py, isort/output.py, isort/settings.py, isort/sorting.py, tests/test_isort.py
Does this look OK as a solution to resolve #1232?
Added a new option that length sorts just the straight imports. It is `off` by default. 
See it in action below with the examples of the OP:
```
▶ cat t.py            
from datetime import timedelta
from contextlib import ExitStack
import os
import datetime
import sys
▶ poetry run isort -d t.py --length-sort-straight
import os
import sys
import datetime
from contextlib import ExitStack
from datetime import timedelta
```
=> Adds length_sort_straight option

isort/output.py, isort/parse.py, tests/test_regressions.py
@timothycrosley please feel free to adjust if needed, but at least it gives you a hint on what is wrong.
Actually it the `# noqa` comment isn't lost, but it is combined up (incorrectly) into the '*' import, but because both of the comments are the same (ie. `noqa`) it is shown only once.
If you changed the second comment to someone else it would should up on the star import, again incorrectly.
BTW, I find it strange that `--combine-star` works for as imports as well.
Is that by design?
Wouldn't that break code that relies on those aliases?
=> Bugfix #1321: --combine-as loses comment

isort/deprecated/finders.py, isort/settings.py, tests/test_isort.py
The first known party path expansion stopped working in 5.0.5. The test for this feature was incorrectly fixed in https://github.com/timothycrosley/isort/commit/1bef08e4a56b07301b5a88c4b79e677f3414173c#diff-3e6dbf50f49313d010ff846279b07462R920 This PR fixes that regression by relying on `Config.directory`.
Thanks @lundberg for the feature and helping out with this PR!
=> Fix the first known party path expansion

tests/integration/test_projects_using_isort.py
There's no need for the history of the repo to check isort. This should increase the speed at which integration tests run and reduce network overhead.
=> integration test clones should be shallow

.cruft.json, .pre-commit-config.yaml, CHANGELOG.md, README.md, docs/configuration/options.md, docs/contributing/1.-contributing-guide.md, docs/major_releases/introducing_isort_5.md, docs/quick_start/0.-try.md, docs/quick_start/2.-cli.md, docs/quick_start/3.-api.md, docs/upgrade_guides/5.0.0.md, docs/warning_and_error_codes/W0500.md, isort/main.py, isort/settings.py, pyproject.toml, rtd/index.md, scripts/build_config_option_docs.py, scripts/check_acknowledgments.py, tests/unit/test_isort.py, tests/unit/test_regressions.py, tests/unit/test_ticketed_features.py
As a result of moving the repo to PyCQA some links were broken.
Some of them were properly redirected, so it is easier to just mechanically change all the references.
Left the following badge links in `README.md` still with old references as they need some setup in the services they are linking to:
- Maintainability badge - codeclimate
- Gitter badge
- DeepSource badge
=> Update timothycrosley references to pycqa

isort/api.py, isort/format.py, tests/unit/test_format.py
Works on the output of `unified_diff` and assumes that all lines starting with a single `+` or a single `-` were marked so by `unified_diff`.
I can't think of a use case when you would have lines starting with a `+` or `-` in the import section where isort operates, so I think it should be fine.
Resolves #1405
=> Adds colors to --diff output.

docs/configuration/action_comments.md
The [documentation](https://pycqa.github.io/isort/docs/configuration/action_comments/) currently lists this as `skip-file`, whereas the default in settings.py has an underscore: https://github.com/PyCQA/isort/blob/cf44d6720f27973cdb54a48bbe8b91bae9055821/isort/settings.py#L31-L34
Am assuming people might be relying on the actual implementation, so changing the documentation is the most reasonable course (absent knowledge of intention)
This had me confused for a bit!
=> Fix documentation for skip_file action comment

isort/core.py, tests/unit/test_regressions.py
Fixes #1420: isort in the case of a line between imports and doc string was incorrectly including the new imports in the comparison,  making it believe the code was always being changed.
=> Fix #1420: Ensure isort doesn't include new imports in comparison

isort/api.py
This pull request fixes the warnings reported by isort.api.sort_file, which currently do not report the same filepath that was actually used in the preceding code; incorrectly reporting "None" in some cases.
=> Bugfix: file_path in warnings in isort.api.sort_file

isort/output.py, isort/parse.py, tests/unit/test_regressions.py
Fixes #1431: Ensuring "as" comments stay connected to the imports they were commented on
=> Resolve #1431: isort incorrectly moving comments

scripts/lint.sh
Now aligns with isort lowest supported version as well as other tools
like mypy.
=> Make black target Python version 3.6

setup.cfg
@timothycrosley I guess you get warnings as well when running pytest?
I don't like scrolling back through them to get to the diffs etc., so I used these filters locally for a while.
Maybe worth adding to the repo?
=> Get rid of warnings displayed when running pytest.

setup.cfg
W503 is ignored by default. Use extend ignore to modify the defaults
rather than override them.
=> Simplify flake8 configuration

poetry.lock, pyproject.toml
Never imported directly by isort, so don't list it as a dependency. When
it is necessary as a transient dependency, that is handled by isort's
direct dependencies.
=> Remove unused optional dependency tomlkit

README.md, isort/wrap_modes.py, tests/unit/test_wrap_modes.py
Implements #1434: Adds an additional wrap mode for grid that doesn't use parentheses.
=> Resovle #1434 add backslash-grid mode

isort/wrap.py, tests/unit/test_ticketed_features.py
Resolves #1456 and #1415: noqa comments shouldn't be moved to where flake8 can't see them
=> Improve isort handling of noqa comments on wrap

isort/settings.py, tests/unit/test_isort.py
=> Fix warnings can't surpressed with quiet.

docs/configuration/profiles.md, isort/profiles.py
PyCharm by default adds 2 lines after imports using the "Optimize Imports (control+option+o)" action.
=> Improve PyCharm Profile

docs/configuration/github_action.md
Closes https://github.com/PyCQA/isort/issues/1493
=> Add documentation for Github Actions

pyproject.toml
Hi,
Tests should not be listed under packages, otherwise setup.py attempts to install a "tests" package, causing potential clashes with other packages.
Comparison of the generated setup.py files before and after the change:
```diff
--- a/setup.py   2020-10-10 19:30:58.737358684 +0200
+++ b/setup.py  2020-10-10 19:31:06.787331020 +0200
@@ -6,28 +6,10 @@
'isort._future',
'isort._vendored.toml',
'isort.deprecated',
- 'isort.stdlibs',
- 'tests',
- 'tests.integration',
- 'tests.unit',
- 'tests.unit.example_projects.namespaces.almost-implicit.root',
- 'tests.unit.example_projects.namespaces.almost-implicit.root.nested',
- 'tests.unit.example_projects.namespaces.implicit.root.nested',
- 'tests.unit.example_projects.namespaces.none.root',
- …
```
=> Prevent installation of the "tests" package

.pre-commit-hooks.yaml, docs/upgrade_guides/5.0.0.md
In #1494, it looks like support for `.pxd` files was added. However, these are currently ignored when running isort in pre-commit because there is `types: [python]`
=> Let pre-commit sort pxd files too

docs/configuration/compatibility_black.md
=> add compatibility docs with black

isort/__init__.py, isort/api.py, isort/core.py, isort/main.py, pyproject.toml, tests/unit/test_api.py, tests/unit/test_main.py
=> CLI to get imports from file

isort/api.py, isort/comments.py, isort/core.py, isort/deprecated/finders.py, isort/literal.py, isort/main.py, isort/output.py, isort/parse.py, isort/settings.py, isort/setuptools_commands.py, isort/sorting.py, isort/stdlibs/__init__.py, isort/wrap_modes.py
"Safe" warnings, regarding style, and ternary operators were fixed.
added some variable initialisations to suppress false-positive "possibly unbound" warnings
"Unused arguments" warnings were left untouched, as they might be used as kwargs and renaming/removing them might break stuff.
Fixes #1569 (does more than the issue suggests, but the deepsource.io link was the basis of the commit.
=> fix deepsource.io warnings

README.md, docs/configuration/options.md, isort/main.py
Trying this one from a different angle...
Previously, if any of the default sections were omitted in a setup.cfg that defined a sections block, isort would throw an exception (see linked issues). Any omitted default sections are now appended to `chain(sections, forced_separate)` during parsing. Duplicates are avoided and the correct (default) order is maintained with an OrderedDict().
Fixes #1570 #1562
=> Handle errors when default section(s) forgotten

isort/main.py
Added these groups: 
- general
- target
- general output
- section output
- deprecated
Also moved arguments a bit because of new grouping.
Generated output: https://gist.github.com/infinityxxx/c4f8c6063e982d4f3bbe8e1a3a433c79
Closes https://github.com/PyCQA/isort/issues/880
=> Group options in help

isort/profiles.py
Black for Python ignores the files listed in .gitignore.
Update the profile to follow that
Fixes #1585
=> Profile: follow black behaviour with regard to gitignore

isort/api.py, tests/unit/test_ticketed_features.py
This will allow the following to be used:
isort_diff = StringIO()
isort_output = StringIO()
isort.file("x.py",
show_diff=isort_diff,
output=isort_output)
Fixes #1583
=> Implement custom output handling in sort_file

docs/configuration/config_files.md
As visible in [code](https://github.com/PyCQA/isort/blob/develop/isort/settings.py#L626-L628).
=> Fix description of config lookup

.pre-commit-hooks.yaml
For details on how pre-commit chooses a default language version, see:
https://pre-commit.com/#overriding-language-version
> For each language, they default to using the system installed language
On some platforms this could be Python 2. As isort is Python-3-only,
this should be enforced in the pre-commit hook. As this isn't currently
listed, some projects have been forced to override it.
=> Set pre-commit language_version to python3

.pre-commit-hooks.yaml
Since pre-commit 2.9.0 (2020-11-21), the types_or key can be used to
match multiple disparate file types. For more upstream details, see:
https://github.com/pre-commit/pre-commit/issues/607
=> Add pyi and cython file support to .pre-commit-hooks.yaml

.pre-commit-hooks.yaml
(seeing as you're now using `types_or` - else the error messages people get may be a bit mysterious)
=> Put minimum pre-commit version in hook

docs/configuration/black_compatibility.md
In reference to https://github.com/PyCQA/isort/issues/1617.
=> Specify the config file example corresponds to pyproject.toml

isort/main.py, isort/output.py, isort/settings.py, isort/sorting.py, tests/unit/test_isort.py
force_sort_within_sections only looked at the order_by_type
option to determine how to order imports with different case
in a section. Whether you order import names by type or not
also affected the order of the modules.
When force_sort_within_sections is used:
* ignore case on the module name if case_sensitive is false,
* ignore case on the imported names if order_by_type is false.
=> Make force_sort_within_sections respect case

isort/output.py, isort/sorting.py
sorting.section_key() is only used once and all its arguments
come from Config. Make it take a single config parameter instead
of a bunch of individual settings.
Follow-up to #1626
=> Simplify section_key helper function arguments

isort/main.py
When using --quiet, no warnings are printed about skipped and
broken paths. But you do get warnings when using the "quiet"
setting in a config file.
Be consistent and don't print the warnings then either.
Fix for #1650.
=> Don't print skipped/broken files with quiet config setting

CHANGELOG.md, docs/configuration/profiles.md, isort/profiles.py, tests/unit/profiles/test_wemake.py
cc @sobolevn 
An initial proposal for a wemake isort profile. Closes #1661
=> Issue #1661: Add wemake profile

isort/core.py, tests/unit/test_ticketed_features.py
When there is no change to the imports but the literal are changed (i.e. sorted by isort), isort doesn't replace the source file with the sorted file. This pull request fixes the problem.
=> Fix not replacing the source file if only literals are changed

README.md
For `isort .` and `isort **/*.py` to be equivalent, one must have `globstar` enabled. This PR adds a small clarifying note to that effect.
Addresses #1665
=> Add clarifying note on globstar to README.md

isort/settings.py, tests/unit/test_settings.py
When I configured isort in the `pyproject.toml`, an error occurred: `Failed to pull configuration information from pyproject.toml`.
After further analysis, it is because pyproject.toml contains many non-ASCII characters, which causes the system default encoding to fail to open.
This pull request added a test case to reproduce the problem and fixes it.
=> fix :Failed to pull configuration information from pyproject.toml

isort/main.py, isort/settings.py, isort/sorting.py, tests/unit/test_isort.py, tests/unit/test_regressions.py
Relative import sort order when using force_sort_within_sections
was inconsistent with the order without that setting. Change the
force_sort_within_sections sort order to match.
This fixes the relative import ordering issues noted in #1659.
Even though all the existing tests still pass (with only one minor test change), the change to the ordering might be significant enough that this needs to be hidden behind a new setting until 6.x?
=> Sort relative imports correctly with force_sort_within_sections

isort/main.py
The --skip option only handles full file paths or names of
individual path components.
For example, "foo/bar/baz.py" can be used to skip just that file.
And "foo" would skip any files with that name and any files nested
in directories with that name.
On the other hand, "foo/bar" does *not* skip everything in the
"foo/bar" directory. --skip-glob can be used to achieve this.
Attempt to clarify the documentation to say that.
Potential fix for #1685. Alternative to #1690.
=> Clarify documentation for --skip option

isort/core.py, tests/unit/test_isort.py
If a multiline docstring has its closing quotes at the end of a line
instead of on a separate line, isort fails to properly add imports using
the `add_imports` config option; instead, it adds the desired imports
into the middle of the docstring as illustrated below. While PEP 257
(and other guides) advises that closing quotes appear on their own line,
`isort` should not fail here.
This change adds a check for closing docstrings at the end of a line in
addition to the existing line start check for all comment indicators. A
new section of the `test_add_imports` test explicitly tests multiline
imports and this failure scenario specifically.
---
A working example:
```python
"""My module.
Provides example functionality.
"""
print("hello, world")
```
Running `isort --add-import "from __future__ …
=> Fix bug regarding multiline docstrings

isort/files.py, tests/unit/test_main.py
Hi,
I found a bug regarding the `--gitignore` CLI flag.
When a file is ignored in .gitignore and you use a relative path, this file won't be skipped.
For example, if I have a file `nested_dir/has_imports.py` in my .gitignore, doing :
```bash
isort . --gitignore
```
will fix `nested_dir/has_imports.py`. Meanwhile :
```bash
isort $(pwd) --gitignore
```
will skip it, as intended.
This PR fixes this by always using an absolute import when checking if a file has to be skipped.
=> Fix --gitignore flag not working on relative subdir files

isort/format.py
=> Initialize `colorama` with `strip=False` to force color for non-tty output.

docs/configuration/options.md
Add note that --atomic is not compatible with Cython, as noted in #1722 
I've written "not compatible with Cython", but please shout up if "only compatible with pure Python" would be better wording (is anything except Python and Cython supported?).
=> Update options.md regarding --atomic and Cython

CHANGELOG.md, isort/output.py, tests/unit/test_ticketed_features.py
=> Fix issue #1726: isort ignores reverse_sort when force_sort_within_sections is true.

isort/api.py, poetry.lock, pyproject.toml, tests/benchmark/test_api.py
Changed not to create `.isorted` tmp files when `--overwrite-in-place` option is specified.
This change reduces redundant disk IOs and improves performance only when the option is enabled.
Now it uses in-memory buffers instead.
`.isorted` files are created by isort and finally swapped for the original files.
It's not necessary process when overwriting original files directly.
Here are the benchmark results.
```
poetry run pytest tests/benchmark/test_api.py
```
```
---------------------------------------------------------------------------------- benchmark: 2 tests ----------------------------------------------------------------------------------
Name (time in ms)              Min               Max              Mean            StdDev            Median               IQR            Outliers …
```
=> Avoid creating tmp_file if --overwrite-in-place option is enabled.

isort/settings.py, tests/unit/test_main.py
This PR addresses #1628 
The method I used is to keep in memory every gitignored files of checked folders. This reduces ``git -check-ignore`` calls which should be enough to improve significantly the ``--gitignore`` speed.
For now I haven't really tested it and there's room for optimization.
Let me know if you agree with the concept.
=> Faster gitignore

docs/configuration/options.md, isort/api.py, isort/format.py, isort/main.py, isort/settings.py, tests/unit/test_format.py
Resolves #961
It adds 2 options : `--format-errors` and `--format-success` overriding the `BasicPrinter` messages
=> add format-errors and format-success options

docs/configuration/options.md, isort/main.py, isort/output.py, isort/settings.py, isort/sorting.py, tests/unit/test_isort.py
recreated branch from https://github.com/PyCQA/isort/pull/1752
=> 1732 adds sort_order allowing pythonic sort as an option

isort/settings.py
The number of files in a project could be larger than the limit on command-line arguments. Using a pipe avoids running into this issue.
Fixes #1758
=> Use a pipe to pass filenames to git check-ignore

isort/settings.py
- Disable core.quotePath
- Use -z to switch from linefeed to null-byte delimiting
This fixes #1760
=> Avoid git octal escaping

docs/configuration/options.md, isort/settings.py, tests/unit/test_settings.py
As discussed in #1704, this adds support for glob expansion in paths provided with the `src_paths` config.
=> Add support for glob expansion in src_paths

isort/settings.py
This PR fixes 3 problems with the current `.gitignore` implementation:
1) Currently, if you have any symbolic links in your project, the `git check-ignore` call in `_check_folder_gitignore` just dies and spams the console with `fatal: pathspec ... is beyond a symbolic link`.
The first commit fixes this issue by replacing `glob.glob(recursive=True)` with `Path.rglob`, since `Path.rglob` doesn't recurse into symlinked directories.
---
Currently, the `file_path` argument of `Config.is_skipped` can be either an absolute or a relative path. I think, that directory paths are always passed as relative, while file paths are always passed as absolute, but don't quote me on that.
If it is a relative path, then the `skip_gitignore` code doesn't work correctly. This is fixed by the second commit, …
=> Some git ignore fixes

isort/pylama_isort.py
usually passed via `[pylama:isort]` section in `pylama.ini` configuration file
close #1779
=> [pylama plugin] process parameters passed to Linter.run()

.pre-commit-hooks.yaml
The PR which led to pre-commit 2.9.0 was [made by a data scientist](https://github.com/pre-commit/pre-commit/pull/1677) and so it [contains a bug](https://github.com/pre-commit/pre-commit/issues/1718), it'd be better to have 2.9.2 as the minimum version - at least, that's what Anthony Sottile suggested be done in `black` https://github.com/psf/black/pull/1875#discussion_r550571589
=> Update minimum pre-commit version to 2.9.2

isort/parse.py, tests/unit/test_isort.py
Based on issue #1807 where the error message is directly printed on the console, rather than raising the `MissingSections` exception with the more descriptive error message.
=> More extensive exception handling

isort/core.py, isort/settings.py, tests/unit/test_isort.py
I had the issue that I wrote a test for darker (https://github.com/akaihola/darker/pull/230) where I get an error because isort is handling every # isort: skip_file even if this is not a real comment.
=> only skip real comments

isort/core.py, isort/settings.py, tests/unit/test_isort.py
=> Revert "only skip real comments"

docs/configuration/config_files.md
Adding documentation clearly underlining how to use the `--resolve-all-configs` flag and when it can be useful.
=> Add multiple config documentation

docs/configuration/options.md
This merge request adds examples for frozen sets and tuple settings for `.isort.cfg` and `pyproject.toml` .
Part of #1729
=> doc: Add examples for frozenset and tuple settings

docs/configuration/config_files.md
When I set the following config in `tox.ini`
```
[isort]
profile = "black"
multi_line_output = 3
```
I am getting the following error when running tox on py39:
```
py39 run-test: commands[1] | poetry run isort obplatform -c
Traceback (most recent call last):
File "/home/runner/work/obplatform/obplatform/.tox/py39/bin/isort", line 8, in <module>
sys.exit(main())
File "/home/runner/work/obplatform/obplatform/.tox/py39/lib/python3.9/site-packages/isort/main.py", line 1108, in main
config = Config(**config_dict)
File "/home/runner/work/obplatform/obplatform/.tox/py39/lib/python3.9/site-packages/isort/settings.py", line 365, in __init__
raise ProfileDoesNotExist(profile_name)
isort.exceptions.ProfileDoesNotExist: Specified profile of "black" does not exist. Available profiles: …
```
=> Add tox config example

docs/configuration/black_compatibility.md
According to the profiles documentation:
https://pycqa.github.io/isort/docs/configuration/profiles.html
The black profiles contains: "multi_line_output = 3". Avoid confusion on
the "Compatibility with black" page by not adding a redundant option.
The reader may believe the extra "multi_line_output" is required.
This came up in a real world scenario:
https://github.com/pypa/pep517/pull/137#discussion_r756648644
=> Remove redundant `multi_line_output = 3` from "Compatibility with black"

isort/core.py, tests/unit/test_isort.py
Resolves #1854
Empty lines just before import sections were always written back in the output.
=> Fix lines_before_imports appending lines after comments

isort/core.py, isort/main.py, isort/settings.py
This PR adds a `--sort-reexports` CLI flag and the respective cfg and toml options to isort, which allows for similar behaviour to `# isort: [list|tuple|dict]` without the need to have comments scattered around. See #1862 for more information.
This PR makes no attempt to document this feature at present, but I'm happy to do this if you'd like me to.
Closes #1862.
=> Add a command-line flag to sort __all__ re-exports (#1862)

isort/profiles.py
Fixes https://github.com/PyCQA/isort/issues/1925
The Plone-related tests pass, three others fail. Should be unrelated, or maybe a bad setup locally:
```
FAILED tests/unit/test_literal.py::test_value_assignment_list - isort.exceptions.FormattingPluginDoesNotExist: Specified formatting plugin of example does not exist.
FAILED tests/unit/test_ticketed_features.py::test_isort_supports_formatting_plugins_issue_1353 - isort.exceptions.FormattingPluginDoesNotExist: Specified formatting plugin of example does not exist.
FAILED tests/unit/test_ticketed_features.py::test_isort_literals_issue_1358 - isort.exceptions.FormattingPluginDoesNotExist: Specified formatting plugin of example does not exist.
```
Also, `./scripts/test.sh` fails because some security updates need to be added, so `poetry …
=> Update plone profile: copy of black, plus three settings.

isort/wrap.py
The following currently happens:
`from very.long.module.path cimport thing` becomes 
```
from very.long.module.(
path cimport thing
)
```
=> Split long cython import lines

example_isort_formatting_plugin/pyproject.toml, example_isort_sorting_plugin/pyproject.toml, example_shared_isort_profile/pyproject.toml
The example plugins are declaring a requirement on poetry-core but using
the "main" poetry build backend.  Correct them to use the poetry.core
backend.
=> Fix build-backend values in the example plugins

isort/core.py, tests/unit/test_isort.py
=> Infinite loop for unmatched parenthesis

isort/settings.py
Improve the performance of `--skip-gitignore` by enumerating all **tracked** files instead of all **ignored** files.
Before:
- call `os.walk` for every target directory
- for each git repo it encounters:
- call `os.walk` to walk over all tracked and ignored files
- call `git check-ignore` on all those files to narrow it to only **ignored** files
- for each file it encounters, skip it if it's in the list of ignored files for that repo
After:
- call `os.walk` for every target directory
- for each git repo it encounters:
- call `git ls-files` to get a list of all **tracked** files
- for each file it encounters, skip it if it's not in the list of tracked files for that repo
Closes https://github.com/PyCQA/isort/issues/1895.
=> skip-gitignore: use allow list, not deny list

isort/main.py
(Or perhaps a newline was intended; feel free to edit.)
=> Add missing space in unrecoverable exception message

docs/configuration/options.md, docs/configuration/profiles.md, isort/main.py, isort/output.py, isort/parse.py, isort/settings.py, isort/wrap.py, tests/unit/test_isort.py, tests/unit/test_parse.py, tests/unit/test_wrap.py
Resolves #1683, it adds the `split_on_trailing_comma` option. 
There's an ambiguous case when from imports are split into 2 parts like this :
```python
from lib import (a, b, c,)
from lib import d
```
In this case I made the choice to always make it split whenever one of the from imports has a trailing comma.
The integration test on airflow won't work until https://github.com/apache/airflow/pull/20556 is passed
=> Add magic trailing comma option

docs/configuration/options.md
Backslashes are different from slashes.
I was looking for this option so I searched for "backslash", found no hits, and assumed it didn't exist.  I only found it later by accident.
=> Clarify description of use_parentheses

docs/quick_start/0.-try.md
The previous deprecated CDN was recently taken down (pyodide/pyodide#3150).
=> Fix Pyodide CDN URL

.github/workflows/test.yml, README.md, docs/configuration/black_compatibility.md, docs/contributing/1.-contributing-guide.md, example_isort_formatting_plugin/poetry.lock, poetry.lock, pyproject.toml, scripts/docker.sh, scripts/lint.sh, tests/integration/test_projects_using_isort.py
=> Remove Python 3.6

.github/workflows/test.yml, .gitignore, isort/_vendored/tomli/_re.py, isort/io.py, isort/settings.py, isort/sorting.py, isort/stdlibs/py311.py, poetry.lock, pyproject.toml, scripts/mkstdlibs.py, scripts/test.sh, tests/unit/test_isort.py, tests/unit/test_parse.py
Closes #1996
Closes #2008
Closes #2011
=> Add Python 3.11 support

.pre-commit-hooks.yaml
Removing language_version enables to use default_language_version.
See: https://github.com/PyCQA/isort/issues/1988
I think this is the modern way for hook definitions. For example popular pre-commit hook from `black` project does not specify `language_version` anymore, see: https://github.com/psf/black/pull/2430
=> Remove language_version for pre-commit hook

.github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/test.yml
This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions …
=> chore(ci): add minimum GitHub token permissions for workflows

.flake8, poetry.lock, pyproject.toml, tests/integration/test_projects_using_isort.py
=> Fix packaging pypoetry

.github/workflows/release-drafter.yml, .github/workflows/release.yml
When pushing `main` on a fork, the release workflow triggers but, as expected, fails to deploy to PyPI because API tokens are missing from forks:
```
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/          
Invalid or non-existent authentication information. See                
https://pypi.org/help/#invalid-auth for more information.              
```
Before: https://github.com/hugovk/isort/actions/runs/3719681768/jobs/6308688909
Let's skip the release workflow for forks.
After: https://github.com/hugovk/isort/actions/runs/3719767321
Also, whilst the release drafter does work for forks, let's only run that for upstream too.
=> Only run release workflows for upstream

pyproject.toml
Add `format = sdist` to `include` table values to prevent the documentation files from being installed directly into site-packages, i.e.:
/usr/lib/python3.11/site-packages/CHANGELOG.md
/usr/lib/python3.11/site-packages/LICENSE
Originally reported by Anna Vyalkova on https://bugs.gentoo.org/887569.
=> Stop installing documentation files to top-level site-packages

tests/unit/test_isort.py
Remove the `toml` import that is used to determine whether to run `pyproject.toml` test.  Firstly, `toml` has been replaced by `tomli`. Secondly, isort vendors `tomli`, so checking for its availability does not seem to make sense.
=> Remove obsolete `toml` import from the test suite

isort/core.py, tests/unit/test_ticketed_features.py
Here is a test case demostrating the issue. I'll try to produce a patch as well.
=> Added test case and fix for cython pure python import

docs/configuration/options.md
The skip-related options (skip, extend-skip, skip-glob, extend-skip-glob, skip-gitignore) all interact with `filter-files` but don't mention it in their own documentation, and filter-files from its name wouldn't come up in text searches for "skip". Adds a mention of `filter-files` usage to the skip-related options docs.
=> Add more docs about filter-files option

docs/configuration/options.md, isort/core.py, isort/literal.py, isort/main.py, tests/unit/test_isort.py
1. Fixes a big where the line would be duplicated rather than sorted
2. Allows for unbracketed tuples to be sorted
3. Allows sets of re-exports to be sorted
4. Allows literals to be sorted even if there are no spaces between the variable name and the literal
5. Renames numerous variables tied to the re-exporter for clarity
Previously, isort would not be able to sort the following code:
```py
my_list=[2, 3, 1]
```
Now, it sorts it like so:
```py
my_list = [1, 2, 3]
```
Closes #1887.
Closes #1971.
Closes #2037.
=> Fix re-export sorter

tests/integration/test_projects_using_isort.py
None of these skips appear to be necessary nowadays; in 2023, the test passes just fine without them on typeshed.
Even if we want to keep some of these skips, the `f"{tmpdir}/third_party/2and3/yaml/__init__.pyi"` skip should definitely go, since that path doesn't exist in typeshed anymore :)
=> Simplify typeshed integration test

tests/unit/test_ticketed_features.py
There is a small typo in tests/unit/test_ticketed_features.py.
Should read `determination` rather than `detrmination`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, detrmination -> determination

isort/hooks.py
This is useful if certain parts of the code are `isort` compatible,
while others might not be. This happened with us when resolving `merges`,
which caused hooks to inadvertently sort imports of parts of the code
that aren't (yet) compatible with `isort`, leading to unclean diffs/PRs.
=> Add the ability to restrict which directories isort works against

poetry.lock, pyproject.toml
With poetry-core>=1.5.0, the dependencies in extras must be present in the main dependency group.
Fix #2077
=> Fix poetry pip-shims extras dependency

isort/main.py
Fixes #1989
`--filename` is a shortcut setting used only in the stdin case to set
the `settings_path`.
Generally, `--settings-path=<file_path>` == `--filename=<filename>`
should hold.
This functionality was removed in 09734212 (Reuse config when items
passed in through stdin as used when items passed in explicitly).
=> Derive `settings_path` from `--filename`

isort/settings.py, tests/unit/test_settings.py, tests/unit/test_ticketed_features.py
Fixes #1994
isort can run in long processes when used in an editor.  In that scenario it is confusing for users when editing a configuration file does not change isorts outcome.
Remove the caches in `settings.py` completely to re-read the configuration on each run.
This is safe for the CLI case as we here either use the `Trie` implementation which collects all known configuration files beforehand, or we exactly construct one `Config` object based on the first filename, the working dir, or the explicit `settings_path|file` settings.
Not caching is therefore more efficient for the CLI case and more useful for the editor case.
=> Do not cache configuration files

docs/configuration/config_files.md
Hi! Noticed, that the tip block at the end of the Config Files page looks broken. Here's a fix.
=> Fix a tip block styling in the Config Files section

docs/configuration/options.md, isort/settings.py
Pytype stores .pyi files in .pytype that isort shouldn’t check or touch.
=> Skip .pytype directory by default.

docs/configuration/pre-commit.md
Updated the pre-commit setup to version 5.11.5 for the poetry hotfix, while keeping Python 3.7 support.
=> Update version in pre-commit setup to avoid installation issue with poetry 

docs/configuration/profiles.md
split_on_trailing_comma is not actually enabled by the black profile
=> docs: fix black profile documentation

docs/configuration/pre-commit.md
Small PR fixing the isort version number in [pre-commit documentation page](https://pycqa.github.io/isort/docs/configuration/pre-commit.html)
=> Update pre-commit.md version number

isort/profiles.py, tests/unit/profiles/test_wemake.py
[Root issue](https://github.com/PyCQA/isort/issues/2182)
Fixed the line length for `wemake` profile to be 79 to comply with linter.
Wrote negative test
=> Fix 80 line length for `wemake` linter

isort/identify.py, isort/parse.py, tests/unit/test_parse.py
=> Added a fix for normalizing imports from more than one level of parent modules (issue/2152)

tests/integration/test_projects_using_isort.py
The following projects don't use isort anymore and use ruff instead: 
- tmuxp - https://github.com/tmux-python/tmuxp/blob/master/pyproject.toml#L151
- fastapi - https://github.com/tiangolo/fastapi/blob/master/pyproject.toml#L130
- websockets - https://github.com/python-websockets/websockets/blob/main/pyproject.toml#L85
- typeshed - https://github.com/python/typeshed/blob/main/pyproject.toml#L29
- poetry - https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L113
- pillow - https://github.com/python-pillow/Pillow/blob/main/pyproject.toml#L103
- attrs - https://github.com/python-attrs/attrs/blob/main/pyproject.toml#L231
- DataDog - https://github.com/DataDog/integrations-core/pull/14212/files
=> Fix integration tests

poetry.lock, pyproject.toml
=> Fix colors extras

.pre-commit-hooks.yaml
See https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
> If you are authoring a tool, it is usually a good idea to provide an appropriate `stages` property. For example a reasonable setting for a linter or code formatter would be `stages: [pre-commit, pre-merge-commit, pre-push, manual]`.
=> confine pre-commit to stages

isort/parse.py, isort/wrap.py, tests/unit/test_wrap.py
Closes #2154 
1. Moved the fix for Issue 471 under the use_parentheses=True condition as it fixes the situation where we added a closing bracket after the comment at line 131.
2. Added tests for the issue #2154 
3. Renamed `_comment` to `noqa_comment`
=> Apply the bracket fix from issue 471 only for use_parentheses=True

isort/core.py, tests/unit/test_isort.py
Fixes #2193 and fixes #2252,
The logic behind `sort_reexports` was keeping track of a point in the `output_stream`, and seeked to that point before writing the sorted reexports back in, in order to compensate for the first line of this code sorting section being written into the stream already.
The original code tried to track the position of the point with every iteration, but since the code is very branched, and contains ~10 `.write` statements, this fails, and this approach would never be easily maintained. So I opted to simplify the approach by instead rolling back the write position in the stream by the length of the segment that was written too much.
Additionally, when the input code sort section is longer than the sorted output (e.g., when there is a lot of trimmed whitespace), …
=> Fix `sort_reexports` code mangling

.pre-commit-hooks.yaml
`pre-commit` v4.0.0 added a warning to deprecated stage names[1] so update these names to avoid the warning. This also required updating the minimum `pre-commit` version to one that supports the new names
See also[2] for a similar change and the docs[3].
[1] https://github.com/pre-commit/pre-commit/blob/cc4a52241565440ce200666799eef70626457488/CHANGELOG.md#400---2024-10-05
[2] https://github.com/pre-commit/pre-commit-hooks/commit/003dfa55c9eb05b08b33f60864363392958f4618
[3] https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
Fixes: https://github.com/PyCQA/isort/issues/2294
=> Update stage names for `pre-commit`

.github/dependabot.yml
Dependabot can automatically look for updated GH actions and rise a PR.
Since dependabot can be very annoying and spam a lot of PRs the GH actions related PRs are grouped into one single PR. Also the update frequency is limited to monthly.
#2299
=> feat: add dependabot for GH action update

.github/workflows/integration.yml, .github/workflows/lint.yml, .github/workflows/test.yml
[GitHub is shutting down this old action version on February 1st, 2025](https://github.blog/changelog/2024-09-16-notice-of-upcoming-deprecations-and-changes-in-github-actions-services/).
In addition, its usage here is no longer needed, because new versions of `actions/setup-python` can do this caching.
@DanielNoord As noted above, this is a time-sensitive PR because `actions/cache@v2` will be removed from GitHub soon.
=> Eliminate `actions/cache@v2` usage

isort/sorting.py, tests/unit/profiles/test_google.py
=> fix: correct group by package tokenization

isort/profiles.py
Updated the google profile to match the style guide
=> Update line_length and single_line_exclusions in google profile

tests/unit/profiles/test_google.py
Fixes regression `main` after merging https://github.com/PyCQA/isort/pull/2149
cc @staticdev
=> Fix google style test

docs/configuration/profiles.md, isort/profiles.py, tests/unit/profiles/test_black.py
When `black` encounters a trailing comma in the `from ... import` list, it expands it vertically. Currently, `isort --profile=black` doesn't do that, which confuses people (including me :)), see #2128.
This PR enables `split_on_trailing_comma`, which is the default Black's behavior.
_I wasn't sure if I should create a new changelog version header, so i omitted it, since that would require deciding whether this is PATCH or MINOR._
---
What Black does:
```
$ echo "from x import (a, b, c,)" | black -
from x import (
a,
b,
c,
)
reformatted -
All done! ✨ 🍰 ✨
1 file reformatted.
```
What isort does _currently_:
```
$ echo "from x import (a, b, c,)" | isort --profile=black -
from x import a, b, c
```
After this change:
```
$ echo "from x import (a, b, c,)" | isort --profile=black -
from x import …
```
=> Black profile: enable magic comma

isort/output.py, tests/integration/test_projects_using_isort.py, tests/unit/profiles/test_black.py, tests/unit/test_isort.py
Closes https://github.com/PyCQA/isort/issues/2338
Took the tests as recommended in https://github.com/PyCQA/isort/pull/2339
I don't think we should fix the tests by disabling the new profile flag, that would mean that our tests work but anybody using the profile would still get broken imports.
Instead, let's try to fix `config.split_on_trailing_comma` itself. I believe this does this.
=> Ensure that split_on_trailing_comma works with `as` imports

isort/core.py, isort/deprecated/finders.py, isort/identify.py, isort/literal.py, isort/main.py, isort/output.py, isort/parse.py, isort/place.py, isort/settings.py, isort/sorting.py, isort/wrap_modes.py, scripts/build_profile_docs.py, tests/integration/test_hypothesmith.py, tests/integration/test_setting_combinations.py, tests/unit/test_deprecated_finders.py, tests/unit/test_hooks.py, tests/unit/test_main.py
Some optimizations for performance or readability.
% `ruff check --select=C4,E713,FLY,PERF401,PIE810,PLC0414,RUF005,RUF010,RUF021,SIM118,SIM201,UP004,UP033,W`
```
15	RUF005 	[*] collection-literal-concatenation
10	RUF010 	[*] explicit-f-string-type-conversion
7	RUF021 	[*] parenthesize-chained-operators
4	E713   	[*] not-in-test
3	PIE810 	[*] multiple-starts-ends-with
3	PERF401	[ ] manual-list-comprehension
2	SIM118 	[*] in-dict-keys
1	C413   	[*] unnecessary-call-around-sorted
1	C417   	[*] unnecessary-map
1	SIM201 	[*] negate-equal-op
1	FLY002 	[*] static-join-to-f-string
1	PLC0414	[*] useless-import-alias
1	UP004  	[*] useless-object-inheritance
1	UP033  	[*] lru-cache-with-maxsize-none
[*] fixable with `ruff check --fix`
```
https://docs.astral.sh/ruff/rules
---
I do not understand …
=> Apply some ruff rules

docs/contributing/2.-coding-standard.md, isort/output.py, isort/settings.py, pyproject.toml, scripts/build_profile_docs.py, scripts/check_acknowledgments.py, scripts/lint.sh, tests/unit/test_exceptions.py, tests/unit/test_isort.py, uv.lock
As suggested at https://github.com/PyCQA/isort/pull/2353#pullrequestreview-2583241874 let's add the [`ruff` linter](https://docs.astral.sh/ruff).
=> Lint Python code with ruff

isort/api.py, isort/main.py, isort/parse.py, isort/settings.py, isort/setuptools_commands.py, pyproject.toml, tests/unit/test_io.py, tests/unit/test_isort.py
As requested at https://github.com/PyCQA/isort/pull/2359#discussion_r1952337350
Stop ignoring ruff rules
* B017 [`assert-raises-exception`](https://docs.astral.sh/ruff/rules/assert-raises-exception)
* B028 [`no-explicit-stacklevel`](https://docs.astral.sh/ruff/rules/no-explicit-stacklevel)
* E203 [`whitespace-before-punctuation`](https://docs.astral.sh/ruff/rules/whitespace-before-punctuation)
`ruff rule E203 `# is disabled by default in `ruff` (but not `flake8`) because it conflicts with `black` and `ruff format`.
=> Ruff rules B017, B028, and E203

pyproject.toml
Ensures that useful project links appear in the sidebar on `PyPI`. These links help users easily find documentation, source code, releases, and other important resources.
Resolves Issue #2386.
=> Add Project URLs to PyPI Side Panel

isort/hooks.py, isort/settings.py
The `nosec` flags benefit from human-readable explanation, but bandit was seeing the trailing text and throwing warnings:
```
WARNING Test in comment: Needed is not a test name or id, ignoring
WARNING Test in comment: for is not a test name or id, ignoring
WARNING Test in comment: gitignore is not a test name or id, ignoring
WARNING Test in comment: support is not a test name or id, ignoring
```
This is addressed by using another `#` character to hide the text.
=> Resolve bandit warnings

isort/deprecated/finders.py
Fixes _get_files_from_dir_cached test which was failing because of an attribute error due to a typo
=> fix typo in _get_files_from_dir_cached test

docs/configuration/pre-commit.md, docs/upgrade_guides/5.0.0.md
Update outdated version references from 5.13.2 to 6.1.0 in:
- docs/configuration/pre-commit.md (2 occurrences)
- docs/upgrade_guides/5.0.0.md (1 occurrence)
The documentation was showing version 5.13.2 (from December 2023) while the latest release is 6.1.0 (October 2025).
Related issues will be created for:
- Missing CHANGELOG entries for 6.0.0, 6.0.1, 6.1.0
- Missing upgrade guide for 6.0.0
=> docs: update pre-commit examples to version 6.1.0
