PyCQA/isort

ACKNOWLEDGEMENTS.md
isort/isort.py
test_isort.py

Fix mangling of imports that end in "import" or "from".

---

isort/isort.py
isort/main.py
test_isort.py

Support forcing line wrap for from imports

---

isort/isort.py

most of the tools I need to use expect a date to be included with the united diff.

add date to unified diff format

---

isort/main.py

It'd be useful to have this option available as a command-line switch :)

Add command-line switch for combining as imports

---

isort/isort.py
isort/main.py
test_isort.py

force grid wrapping regardles of line length

---

isort/main.py

The command line argument does not work as expected.

Fixed command line argument '--trailing-comma'

---

isort/isort.py
test_isort.py

force_grid_wrap code and setting had different names

---

isort/isort.py
isort/main.py
test_isort.py

Fixes: https://github.com/timothycrosley/isort/issues/271
As it is a bit of an outsider from the rest of the methods I decided to use this approach (basically doing all the sort by myself).
I hope it's acceptable. I event wrote a test, which, btw. was easy and fun! Thanks for having a nice test suite easy to extend!

Sort all imports alphabetically

---

CHANGELOG.md
README.rst
isort/isort.py
isort/settings.py
test_isort.py

This PR adds the option to leave long import lines long and to add a NOQA option.

Adding NOQA Option

---

isort/__main__

Add support to run library as a module #305.

Add support to run library as a module #305

---

isort/isort.py

Better errors if place_module cannot place a module.

---

isort/isort.py

This has been removed in 6a1a78b74.

Remove unused import of stderr

---

isort/isort.py

Fixes https://github.com/timothycrosley/isort/issues/376.
Does it make sense?
Should have a test then.

Do not consider single-letter modules to be constants

---

isort/isort.py

I personally think that check-only shouldn't care about empty lines.  If other people agree, please accept this pull request.  Thanks.

Check-only no longer cares about empty lines

---

README.rst

Also remove unneeded __main__ check.

Add missing shebang and import to git hook

---

CHANGELOG.md
README.rst
isort/isort.py
isort/main.py
isort/pie_slice.py
test_isort.py

* comment
* copies
* extremely
* independent
* running
* their

spelling fixes

---

isort/isort.py
test_isort.py

Fix invalid syntax for noqa output

---

setup.py

technically this works, but it should be four spaces, not three

should match indentation with other parts of code

---

isort/main.py
isort/natural.py

https://docs.python.org/3/whatsnew/3.6.html#deprecated-python-behavior

Python 3.6 invalid escape sequence deprecation fixes

---

CHANGELOG.md
isort/settings.py

Normalize paths for consistent linux/windows usage

---

.travis.yml
isort/pie_slice.py
test_isort.py
tox.ini

My requires.io has been nagging about all the extra releases today. If it really was just issues that would be caught by linting, let me help you out with that so it doesn't happen again. :-)
Resolves #551.

Add linting with flake8 in Travis

---

.travis.yml

https://docs.travis-ci.com/user/caching/#pip-cache

Add pip cache to Travis CI builds

---

isort/isort.py

Show what section each import was placed in, if in verbose mode.
This can help debug differences between systems, in case e.g. some
library was installed on only one of them and therefore was placed
differently.
See also: https://bugzilla.redhat.com/1450161

debug place_module

---

isort/isort.py

It looks nicer if the character the user types appears after a space rather than right next to the question mark.

Add a space after the input string.

---

isort/main.py

A file starting with the line:
```
#!/usr/bin/env python
```
Or
```
#!/usr/bin/python
```
And other variations, are Python scripts and frequently do not have a `.py` extension. These will now also be included by isort processing
---
Use case: I noticed that scripts in my project did not have sorted imports. I want my scripts to go through the same static analysis as the rest of the project.

In iter_source_code() include Python scripts without an extension

---

isort/settings.py
test_isort.py

Fix deprecation warnings on Python 3

---

test_isort.py

repair broken test, I just ported ed99445a updates to test_isort.py back, looks like they weren't kept during a merge conflict

repair broken test

---

isort/__main__.py

Fix `python -m isort ...` under python 2

---

test_isort.py

Updating test to account for django being installed on local machine.

---

isort/__init__.py

This caused me more headache than I'd like to admit.
EDIT: This is noted as "In progress" on the changelog, but this is the version on pypi.

Version bump

---

ACKNOWLEDGEMENTS.md

For a list of past contributions, see:
https://github.com/timothycrosley/isort/commits?author=jdufresne

Add myself to list of code contributors

---

isort/isort.py
test_isort.py

allow for files missing closing newlines in whitespace check

---

isort/settings.py

I fixed issue 690 by removing __init__.py from the default ignore list.

Remove '__init__.py' from skipped list.

---

isort/settings.py

Fixes #729 
To solve this, easiest would be to walk the path up looking for `__init__.py` files until not found anymore and that way find the source root, but since this is python 2 and 3, init files may not be present.
This pull request uses the directory of the config file, setting the known paths as the root dir.
**Example:**
Lets say we have a project in directory `/tmp/myapp` with a `src` dir and a config file:
``` yaml
tmp/
- myapp/
- setup.cfg
- src/
- foo/
- __init__.py
- bar.py
```
``` ini
[isort]
known_first_party = src/
```
Executing `isort bar.py` from `/tmp/myapp/src/foo` will make the path in `known_first_party` absolute while reading the config file `setup.cfg`.
``` py
>>> settings['known_first_party]
['/tmp/myapp/src/']
```

Make known path patterns relative to config file containing the setting

---

isort/main.py

:ambulance: follow symbolic links too when walking the path

---

isort/pie_slice.py

Import from collections.abc to avoid deprecation warning

---

.travis.yml
tox.ini

As a supported platform, it should be tested.

Add pypy3 testing to the test matrix

---

isort/main.py
test_isort.py

Skip files that look like an editor's backup file

---

test_isort.py

Instead of manually creating temporary directories and following through
with the cleanup, use pytest's tmpdir fixtures. It makes writing test
files easier and does automatic cleanup.
https://docs.pytest.org/en/latest/tmpdir.html
By leveraging pytest, can remove a lot of unnecessary code.

Simplify tests using pytest fixtures

---

isort/isort.py

In unit tests, it's more sensical to test for the positive condition, as
in:
assert SortImports(f, check=True).correctly_sorted

Add correctly_sorted property on SortImports

---

isort/isort.py
test_isort.py

Fix issue 576

---

isort/main.py

Fix not skip not being honored

---

.env

Changed distribution function to upload via Twine per issue #828

---

isort/isort.py
test_isort.py

This fixes "no_lines_before" to also be respected from previous empty
sections.

Fix no_lines_before with empty section

---

.travis.yml
appveyor.yml
tox.ini

ci/tests: revisit config/setup

---

codecov.yml

Ref: https://docs.codecov.io/docs/codecov-yaml
For comments: https://docs.codecov.io/docs/pull-request-comments

ci: add codecov.yml

---

CHANGELOG.md
isort/isort.py
isort/main.py
isort/settings.py
test_isort.py

Fix issue #890

---

CHANGELOG.md
isort/isort.py
test_isort.py

Fix issue #889: Isort should not add blank lines to beginning of file

---

CHANGELOG.md
isort/isort.py
test_isort.py

Fix handling of whitespace character

---

test_isort.py

Ensures #691 is fully resolved

Add test case for issue #691

---

isort/__init__.py
isort/compat.py
isort/isort.py
isort/main.py
isort/pylama_isort.py
test_isort.py

To prepare for refactoring of `__init__` method and others.

Make compat layer to preserve public api

---

isort/main.py

#971 
@timothycrosley This is totally a small fix could you check this

bug fix type int for wrap length

---

mypy-requirements.txt
tox.ini

Typing of the stdlib is being updated all the time. Ensure this project
uses an up to date version of mypy for more accurate results.

Unpin mypy requirements

---

isort/settings.py
test_isort.py
tox.ini

Was mistakenly removed in commit
55f1ae707d429c9605f39812b11b9b75140f5749.

Restore lint tox environment

---

isort/finders.py

More Pythonic and friendly to subclassing.

Prefer self.method() over MyClass.method()

---

isort/compat.py
isort/finders.py
isort/format.py
isort/isort.py
isort/main.py
test_isort.py

Helps migrate old Python code to modern standards. Ran with the
--py3-plus flag for to enable all available upgrade options. For details
on pyupgrade, see:
https://github.com/asottile/pyupgrade

Run pyupgrade tool across the project

---

isort/finders.py

This PR addresses issue #1018.

Add src layout support

---

isort/isort.py
test_isort.py

Keep correct comment location with force_sort_within_sections

---

test_isort.py

Add test from issue #751

---

isort/main.py
tests/test_main.py

Add support for automatically skipping over fifo files

---

isort/api.py
tests/test_isort.py

Fixes #1088 and #1089 and #1090

Fix a variety of nested import bugs

---

isort/api.py
isort/parse.py
tests/test_isort.py

Fix issue #1103

---

tests/test_format.py
tests/test_io.py

@ucodery This should fix the testing errors you were experiencing. The test errors, where occasional errors dealing with encoding that weren't correctly specified in hypothesis-auto test cases: https://github.com/timothycrosley/hypothesis-auto

Fix test case to be more explicit

---

isort/output.py
tests/test_isort.py

Fixes issue with as_imports and force_single_section

Fix issue with as_imports and force_single_section

---

.gitignore
isort/api.py
isort/main.py
isort/settings.py
poetry.lock
pyproject.toml
tests/test_isort.py

Fixes bug demonstrated in this pull request https://github.com/timothycrosley/isort/pull/1135

Bryant1410 patch 1

---

tests/test_isort.py

Adds a test confirming issue #1117 is fully resolved.

Add test to ensure issue #1117 is fixed

---

tests/test_isort.py

Confirms #1005 is resolved for 5.0.0 release

Test confirming issue #1005 is fixed

---

pyproject.toml

This link will be shown at https://pypi.org/project/isort/ and makes it easier to find the documentation.

Add link to documentation

---

tests/test_main.py

A test for the `--version` argument. A small step towards 100% test coverage.

test for --version argument

---

pyproject.toml

Background info at
https://github.com/pypa/warehouse/pull/7882#issue-412444446

Add changelog project URL

---

isort/finders.py

Bug fix for improper handling of packages with - (dash) in name

Bug fix for #1221

---

pyproject.toml
scripts/clean.sh
scripts/lint.sh

1. Added black config to pyproject.toml
1. Ensure that other methods of running black use the project's setting

Standardize black config

---

pyproject.toml

fixes part of timothycrosley/isort#1266
fixes timothycrosley/isort#463

pyproject.toml: Add tests in sdist only

---

isort/api.py
tests/test_isort.py

I didn't fully understand the code but it did resolve #1339 and the tests are passing, except:
* ` tests/test_regressions.py::test_windows_newline_issue_1277`

Remove minimum indents under nested condition

---

scripts/check_acknowledgments.py

Hi there, 
I created a script that gets all the authors from the GithHub API https://api.github.com/repos/timothycrosley/isort/contributors and checks whether they are mentioned on the acknowledgment page: https://github.com/timothycrosley/isort/blob/develop/docs/contributing/4.-acknowledgements.md.
Displays all the missing authors with a link to their contribution page, to check what type of contributions they've made.
Example output:
```
Found unacknowledged authors:
- Maksim Kurnikov (@mkurnikov)
https://github.com/timothycrosley/isort/commits?author=mkurnikov
--------------------------------------------------------------------------------
- Daniel Hahler (@blueyed)
https://github.com/timothycrosley/isort/commits?author=blueyed …
```

Adds script that displays unacknowledged authors.

---

isort/wrap_modes.py
tests/test_isort.py
tests/test_wrap_modes.py

Adds a new wrap mode Hanging Indent, With Parentheses (10).
Fixes #941.

Adds new wrap mode 10 - Hanging Indent, With Parentheses.

---

README.md
docs/configuration/options.md
isort/main.py

I could swear I had these in the original PR, but I somehow managed to not commit them and couldn't find them locally either. :-)

Complete documentation for multi line modes.

---

isort/output.py

Hi @timothycrosley,
How do you feel about accepting refactorings in general?
This would be an example.
I would try to keep them short, provide a description of the why and what and of course try to ensure the changes are safe.
Description:
* Remove duplication in handling `from_first` and make the intent clearer.
* `with_from_import` and `with_straight_import` don't need to know or write to the "global" `section_output`
- remove `section_output` argument
- remove `section_output.copy()`
- functions return their own output without knowing about
the "global" output
* `sort_ignore_case` already passed in to `_with_from_imports` in `config`. Just use it from there to simplify the argument list and make the 2 helper function arguments more uniform

Small refactoring in output.py.

---

isort/format.py

Bugfix: 1412 Missing colorama leads to exception

---

example_isort_formatting_plugin/example_isort_formatting_plugin.py
example_isort_formatting_plugin/pyproject.toml
isort/_future/_dataclasses.py
isort/output.py
isort/wrap_modes.py
poetry.lock
pyproject.toml
tests/integration/test_setting_combinations.py
tests/unit/profiles/test_black.py
tests/unit/test_isort.py
tests/unit/test_ticketed_features.py

Add initial profile test suite for black profile

Add black profile test

---

tests/integration/test_projects_using_isort.py
tests/unit/profiles/test_attrs.py
tests/unit/profiles/test_django.py
tests/unit/profiles/test_google.py
tests/unit/profiles/test_hug.py
tests/unit/profiles/test_open_stack.py
tests/unit/profiles/test_plone.py
tests/unit/profiles/test_pycharm.py
tests/unit/utils.py

Fixes #1392: Ensuring each profile has its own dedicated test suite based on real life code examples, with the ability to easily grow overtime.

Add additional profile tests

---

docs/configuration/options.md
docs/upgrade_guides/5.0.0.md
isort/main.py

This PR simply fixes a few typos I've encountered while reading the docs for the package.
Thanks!

Typo fixes

---

isort/format.py
tests/unit/test_format.py
tests/unit/test_isort.py

Print errors to stderr.

---

tests/integration/test_projects_using_isort.py

Need this https://github.com/DataDog/integrations-core/pull/7562
Because of
```
Cloning into '/private/var/folders/kl/jczcp1rd4b1655pzccqbj6140000gn/T/pytest-of-alexandre.yang/pytest-5/test_datadog_integrations_core0'...
ERROR: /private/var/folders/kl/jczcp1rd4b1655pzccqbj6140000gn/T/pytest-of-alexandre.yang/pytest-5/test_datadog_integrations_core0/.gitlab/validate-logs-intgs/validate_log_intgs.py Imports are incorrectly sorted and/or formatted.
ERROR: /private/var/folders/kl/jczcp1rd4b1655pzccqbj6140000gn/T/pytest-of-alexandre.yang/pytest-5/test_datadog_integrations_core0/.azure-pipelines/scripts/sqlserver/windows/40_install_sqlserver.py Imports are incorrectly sorted and/or formatted.
ERROR: /private/var/folders/kl/jczcp1rd4b1655pzccqbj6140000gn/T/pytest-of-alexandre.yang/pytest-5/test_d …
```

Test Datadog integrations-core

---

isort/main.py
tests/unit/test_isort.py
tests/unit/test_main.py

Exit non zero if all of passed path is broken

---

isort/main.py
tests/unit/test_main.py

Check only with stdin

---

tests/unit/test_main.py

Added tests for several CLI flags with stdin. Have a look and highlight if I missed any prominent ones, I'll add those then.

Added tests for different cli flag with stdin

---

isort/literal.py
tests/unit/test_literal.py
tests/unit/test_ticketed_features.py

Fixes #1515.
Bonus: increases branch coverage of literals.py to 100%

Fixes bug in isort-assignments sorting.

---

tests/unit/test_regressions.py

Adds characterization tests for float_to_top and on/off.

Adds characterization tests for float_to_top and on/off.

---

tests/unit/test_main.py

Sorry I previously misplaced the `--only-modified` stdin test in the `test_unsupported_encoding` function, so just corrected that. Also to increase coverage, added another test with `--only-modified` and `--check-only` flags with modified files.

Corrected a misplaced test and added another.

---

isort/api.py
isort/setuptools_commands.py
isort/sorting.py
tests/unit/test_api.py
tests/unit/test_hooks.py
tests/unit/test_isort.py

Takes the branch test coverage to 100% of the following files:
- `api.py`
- `hooks.py`
- `place.py`
- `setuptools_commands.py`
- `sorting.py `
We're almost there, what is still left to do: `output.py`, `parse.py`, and `settings.py`.

Improve test coverage

---

isort/main.py
isort/output.py
isort/settings.py
tests/unit/test_isort.py
tests/unit/test_main.py

Combine bare straight imports in one line

---

tests/unit/test_settings.py

Branch coverage of `settings.py` -> 100%.

Improves test coverage of settings.py.

---

isort/__init__.py
isort/api.py
isort/core.py
tests/unit/test_isort.py

Issue #1536 
I have not yet added new CLI command mentioned in issue. Need to check how it is done in argparse before.

Provide API and CLI to list and stream imports

---

isort/main.py

Fixes #1577: Typo - invalid argument "quite"

Issue/1557 - Fix a typo

---

docs/configuration/options.md
isort/main.py

Add description of `--check` exit status to help message

---

isort/output.py
tests/integration/test_setting_combinations.py

Fixes #1574: Non idempotent behaviour causing flaky integration test

Fix non-idempotent behavior for combine-straight

---

.pre-commit-config.yaml

Run isort on all files to avoid listing them.

Simplify .pre-commit-config.yaml

---

tests/unit/test_wrap_modes.py

The three vertical grid multi line output modes 4, 5 and 6 use a
shared function that makes them all wrap slightly differently when
the import lines are right around the line length limit. Add tests
to document the behavior and catch regressions.
Adds tests for the behavior reported in #1640 and #1634 .

Unit test behavior of vertical grids close to the line length

---

.github/workflows/integration.yml
.github/workflows/lint.yml
.github/workflows/test.yml

https://github.com/actions/cache/releases
https://github.com/actions/setup-python/releases

GitHub Actions: Upgrade actions/cache and actions/setup-python

---

isort/files.py
isort/main.py

See #1709 for more info.
Fixes #1709.

Fix UserWarnings

---

docs/configuration/black_compatibility.md

Fixed typo

---

docs/major_releases/introducing_isort_5.md

Correct links in docs

---

docs/warning_and_error_codes/W0500.md
isort/main.py
isort/settings.py

Related to #1753, I fixed some more broken URLs.

Fix URLs for 5.0.0 upgrade guide

---

docs/configuration/github_action.md

jamescurtin/isort-action no longer exists

Remove reference to jamescurtin/isort-action

---

isort/format.py

Fix Rich compatibility

---

CHANGELOG.md

Fix year of version 5.12.0 in CHANGELOG.md

---

docs/configuration/black_compatibility.md

Update recommended rev to 5.11.5. (5.6.4 has poetry-related issue)

doc: Update black_compatibility.md

---

README.md

https://github.com/PyCQA/isort
https://github.com/hugovk/isort/tree/fix-badges

Fix GitHub Actions badges

---

pyproject.toml

Link GH as changelog

---

.github/dependabot.yml

Let's let `dependabot` notify us of updates here, like it does for `github-actions`.

Add dependabot for `uv`
